function onlyNumber(d){window.netscape?34<d.which&&41>d.which||47<d.which&&58>d.which||95<d.which&&106>d.which||8==d.which||9==d.which||13==d.which||46==d.which||(d.preventDefault?d.preventDefault():d.returnValue=!1):34<d.keyCode&&41>d.keyCode||47<d.keyCode&&58>d.keyCode||95<d.keyCode&&106>d.keyCode||8==d.keyCode||9==d.keyCode||13==d.keyCode||46==d.keyCode||(d.preventDefault?d.preventDefault():d.returnValue=!1)}function GetNode(d,g){return GetNodeIdx(d,g,0)}
function GetNodeIdx(d,g,e){return d.getElementsByTagName(g)[e]}function GetNodeValue(d,g){return GetNodeValueIdx(d,g,0)}function GetNodeValueIdx(d,g,e){d=GetNodeIdx(d,g,e);return GetValue(d)}function GetValue(d){var g="";try{0<d.childNodes.length&&(g=d.firstChild.nodeValue)}catch(e){g="error"}return g}function SetDivinnerHTML(d,g){try{document.getElementById(d).innerHTML=g}catch(e){}}function SetDivouterHTML(d,g){try{document.getElementById(d).outerHTML=g}catch(e){}}
function SetDivText(d,g){try{document.getElementById(d).innertText=g}catch(e){}}
function xmlhttpPostXML(d,g,e,a){var c=!1;window.XMLHttpRequest&&!window.ActiveXObject?(c=new XMLHttpRequest,c.overrideMimeType("text/xml")):window.ActiveXObject&&(c=new ActiveXObject("Microsoft.XMLHTTP"));c.open("GET",d,!0);c.setRequestHeader("Content-Type","application/x-www-form-urlencoded");c.onreadystatechange=function(){4==c.readyState&&eval(e)(c.responseXML,a)};c.send();if(4==c.readyState)switch(g=c.responseXML,c.status){case 404:alert("Error: Not Found. The requested URL "+d+" could not be found.");
break;case 500:handleErrFullPage(g);break;default:-1<g.indexOf("Error:")||-1<g.indexOf("Debug:")?alert(g):eval(e+"(strResponse);")}}
function xmlAdmin(d,g){var e=document.getElementById("xml_value"),a,c,k=GetNode(d,"dext5");if("1"==g){var f=GetNode(k,"license"),b=GetNodeValue(f,"product_key");a=document.createElement("input");a.setAttribute("type","hidden");a.setAttribute("id","product_key");a.setAttribute("name","product_key");a.setAttribute("value",b);e.appendChild(a);""!=b&&(a=b.split("-"),document.getElementById("product_key_1").value=a[0],document.getElementById("product_key_2").value=a[1],document.getElementById("product_key_3").value=
a[2],document.getElementById("product_key_4").value=a[3]);b=GetNodeValue(f,"license_key");document.getElementById("license_key").value=b;c=GetNodeValue(f,"plugin_use");for(b=0;b<dext5_admin_lang.plugin_use_value.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.plugin_use_value[b]),a.innerHTML=dext5_admin_lang.plugin_use_text[b],document.getElementById("plugin_use").appendChild(a),dext5_admin_lang.plugin_use_value[b]==c&&(a.selected=!0);b=GetNodeValue(f,"print_header");
c=GetNodeValue(f,"print_footer");"1"==document.getElementById("plugin_use").value&&(document.getElementById("tr_mime_use").style.display="",document.getElementById("tr_print_preview").style.display="",document.getElementById("tr_print_header").style.display="",document.getElementById("tr_print_footer").style.display="",""!=b?(document.getElementById("chk_print_header").checked=!1,document.getElementById("print_header").disabled=!1,document.getElementById("print_header_desc").innerHTML=dext5_admin_lang.print_header_desc2,
document.getElementById("print_header").value=b):(document.getElementById("print_header").disabled="disabled",document.getElementById("print_header_desc").innerHTML=dext5_admin_lang.print_header_desc1),""!=c?(document.getElementById("chk_print_footer").checked=!1,document.getElementById("print_footer").disabled=!1,document.getElementById("print_footer_desc").innerHTML=dext5_admin_lang.print_footer_desc2,document.getElementById("print_footer").value=c):(document.getElementById("print_footer").disabled=
"disabled",document.getElementById("print_footer_desc").innerHTML=dext5_admin_lang.print_footer_desc1));b=GetNodeValue(f,"mime_use");"1"==b?document.getElementById("mime_use").value="1":document.getElementById("mime_use").value="0";b=GetNodeValue(f,"print_preview");"1"==b?document.getElementById("print_preview").value="1":document.getElementById("print_preview").value="0"}else f=GetNode(k,"license"),b=GetNodeValue(f,"product_key"),a=document.createElement("input"),a.setAttribute("type","hidden"),
a.setAttribute("id","product_key"),a.setAttribute("name","product_key"),a.setAttribute("value",b),e.appendChild(a),b=GetNodeValue(f,"license_key"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","license_key"),a.setAttribute("name","license_key"),a.setAttribute("value",b),e.appendChild(a),c=GetNodeValue(f,"plugin_use"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","plugin_use"),a.setAttribute("name","plugin_use"),"error"==
c?a.setAttribute("value","0"):a.setAttribute("value",c),e.appendChild(a),b=GetNodeValue(f,"mime_use"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","mime_use"),a.setAttribute("name","mime_use"),a.setAttribute("value",b),e.appendChild(a),b=GetNodeValue(f,"print_preview"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","print_preview"),a.setAttribute("name","print_preview"),a.setAttribute("value",b),e.appendChild(a),b=GetNodeValue(f,
"print_header"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","print_header"),a.setAttribute("name","print_header"),a.setAttribute("value",b),e.appendChild(a),c=GetNodeValue(f,"print_footer"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","print_footer"),a.setAttribute("name","print_footer"),a.setAttribute("value",c),e.appendChild(a);GetNode(k,"work_config");if("2"==g){f=GetNode(k,"top_menu");c=f.getElementsByTagName("menu").length;
for(b=0;b<c;b++){var l=GetNodeValueIdx(f,"menu",b);a=document.createElement("option");a.setAttribute("value",l);a.innerHTML=eval("dext5_admin_lang.top_menu."+l);document.getElementById("set_menu").appendChild(a);a=document.createElement("input");a.setAttribute("type","hidden");a.setAttribute("id","top_menu_pre");a.setAttribute("name","top_menu_pre");a.setAttribute("value",l);e.appendChild(a)}for(b=0;b<dext5_admin_lang.top_menu_value.length;b++){a=!1;for(f=0;f<document.getElementById("set_menu").length;f++)if(dext5_admin_lang.top_menu_value[b]==
document.getElementById("set_menu").options[f].value){a=!0;break}a||(a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.top_menu_value[b]),a.innerHTML=dext5_admin_lang.top_menu_text[b],document.getElementById("all_menu").appendChild(a))}}else for(f=GetNode(k,"top_menu"),c=f.getElementsByTagName("menu").length,b=0;b<c;b++)l=GetNodeValueIdx(f,"menu",b),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","top_menu"),a.setAttribute("name","top_menu[]"),
a.setAttribute("value",l),e.appendChild(a);if("3"==g){l=GetNode(k,"tool_bar_1");c=l.getElementsByTagName("tool").length;for(b=0;b<c;b++)f=GetNodeValueIdx(l,"tool",b),a=document.createElement("option"),a.setAttribute("value",f),"c_"==f.substring(0,2)?a.innerHTML=f:a.innerHTML=eval("dext5_admin_lang.tool_bar."+f),document.getElementById("set_menu1").appendChild(a),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","tool_bar_1_pre"),a.setAttribute("name","tool_bar_1_pre"),
a.setAttribute("value",f),e.appendChild(a);l=GetNode(k,"tool_bar_2");c=l.getElementsByTagName("tool").length;for(b=0;b<c;b++)f=GetNodeValueIdx(l,"tool",b),a=document.createElement("option"),a.setAttribute("value",f),"c_"==f.substring(0,2)?a.innerHTML=f:a.innerHTML=eval("dext5_admin_lang.tool_bar."+f),document.getElementById("set_menu2").appendChild(a),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","tool_bar_2_pre"),a.setAttribute("name","tool_bar_2_pre"),a.setAttribute("value",
f),e.appendChild(a);for(b=0;b<dext5_admin_lang.tool_bar_value.length;b++){a=!1;for(f=0;f<document.getElementById("set_menu1").length;f++)if(dext5_admin_lang.tool_bar_value[b]==document.getElementById("set_menu1").options[f].value){a="separator"==document.getElementById("set_menu1").options[f].value?!1:!0;break}for(f=0;f<document.getElementById("set_menu2").length;f++)if(dext5_admin_lang.tool_bar_value[b]==document.getElementById("set_menu2").options[f].value){a="separator"==document.getElementById("set_menu2").options[f].value?
!1:!0;break}a||(a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.tool_bar_value[b]),a.innerHTML=dext5_admin_lang.tool_bar_text[b],document.getElementById("all_menu").appendChild(a))}}else{l=GetNode(k,"tool_bar_1");c=l.getElementsByTagName("tool").length;for(b=0;b<c;b++)f=GetNodeValueIdx(l,"tool",b),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","tool_bar_1"),a.setAttribute("name","tool_bar_1[]"),a.setAttribute("value",f),e.appendChild(a);
l=GetNode(k,"tool_bar_2");c=l.getElementsByTagName("tool").length;for(b=0;b<c;b++)f=GetNodeValueIdx(l,"tool",b),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","tool_bar_2"),a.setAttribute("name","tool_bar_2[]"),a.setAttribute("value",f),e.appendChild(a)}if("4"==g){l=GetNode(k,"status_bar");c=l.getElementsByTagName("status").length;for(b=0;b<c;b++)f=GetNodeValueIdx(l,"status",b),a=document.createElement("option"),a.setAttribute("value",f),a.innerHTML=eval("dext5_admin_lang.status_bar."+
f),document.getElementById("set_menu").appendChild(a),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","status_bar_pre"),a.setAttribute("name","status_bar_pre"),a.setAttribute("value",f),e.appendChild(a);for(b=0;b<dext5_admin_lang.status_bar_value.length;b++){a=!1;for(f=0;f<document.getElementById("set_menu").length;f++)if(dext5_admin_lang.status_bar_value[b]==document.getElementById("set_menu").options[f].value){a=!0;break}a||(a=document.createElement("option"),
a.setAttribute("value",dext5_admin_lang.status_bar_value[b]),a.innerHTML=dext5_admin_lang.status_bar_text[b],document.getElementById("all_menu").appendChild(a))}}else for(l=GetNode(k,"status_bar"),c=l.getElementsByTagName("status").length,b=0;b<c;b++)f=GetNodeValueIdx(l,"status",b),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","status_bar"),a.setAttribute("name","status_bar[]"),a.setAttribute("value",f),e.appendChild(a);if("5"==g){l=GetNode(k,"remove_item");
c=l.getElementsByTagName("item").length;for(b=0;b<c;b++)f=GetNodeValueIdx(l,"item",b),a=document.createElement("option"),a.setAttribute("value",f),a.innerHTML=eval("dext5_admin_lang.remove_item."+f),document.getElementById("set_menu").appendChild(a);for(b=0;b<dext5_admin_lang.remove_item_value.length;b++){a=!1;for(f=0;f<document.getElementById("set_menu").length;f++)if(dext5_admin_lang.remove_item_value[b]==document.getElementById("set_menu").options[f].value){a=!0;break}a||(a=document.createElement("option"),
a.setAttribute("value",dext5_admin_lang.remove_item_value[b]),a.innerHTML=dext5_admin_lang.remove_item_text[b],document.getElementById("all_menu").appendChild(a))}}else for(l=GetNode(k,"remove_item"),c=l.getElementsByTagName("item").length,b=0;b<c;b++)f=GetNodeValueIdx(l,"item",b),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","remove_item"),a.setAttribute("name","remove_item[]"),a.setAttribute("value",f),e.appendChild(a);if("6"==g)for(l=GetNode(k,"font_size"),
c=l.getElementsByTagName("size").length,b=0;b<c;b++){var h=GetNodeValueIdx(l,"size",b);a=document.createElement("option");a.setAttribute("value",h);a.innerHTML=h;document.getElementById("set_font_size").appendChild(a)}else for(l=GetNode(k,"font_size"),c=l.getElementsByTagName("size").length,b=0;b<c;b++)h=GetNodeValueIdx(l,"size",b),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","font_size"),a.setAttribute("name","font_size[]"),a.setAttribute("value",h),e.appendChild(a);
if("7"==g){l=GetNode(k,"font_family");c=l.getElementsByTagName("font").length;for(b=0;b<c;b++)h=GetNodeValueIdx(l,"font",b),a=document.createElement("option"),a.setAttribute("value",h),a.innerHTML=h,document.getElementById("set_font_family").appendChild(a);for(b=0;b<dext5_admin_lang.font_family.length;b++){a=!1;for(f=0;f<document.getElementById("set_font_family").length;f++)if(dext5_admin_lang.font_family[b]==document.getElementById("set_font_family").options[f].value){a=!0;break}a||(a=document.createElement("option"),
a.setAttribute("value",dext5_admin_lang.font_family[b]),a.innerHTML=dext5_admin_lang.font_family[b],document.getElementById("all_font_family").appendChild(a))}}else for(l=GetNode(k,"font_family"),c=l.getElementsByTagName("font").length,b=0;b<c;b++)h=GetNodeValueIdx(l,"font",b),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","font_family"),a.setAttribute("name","font_family[]"),a.setAttribute("value",h),e.appendChild(a);if("8"==g){f=GetNode(k,"setting");b=GetNodeValue(f,
"grid_color");a=document.createElement("input");a.setAttribute("type","hidden");a.setAttribute("id","grid_color");a.setAttribute("name","grid_color");a.setAttribute("value",b);e.appendChild(a);c=GetNodeValue(f,"grid_color_nm");a=document.createElement("input");a.setAttribute("type","hidden");a.setAttribute("id","grid_color_nm");a.setAttribute("name","grid_color_nm");a.setAttribute("value",c);e.appendChild(a);""==b?(document.getElementById("grid_color_value").style.backgroundColor="#8b0000",document.getElementById("grid_color_text").innerHTML=
"Dark Red"):(document.getElementById("grid_color_value").style.backgroundColor=b,document.getElementById("grid_color_text").innerHTML=c);a=document.createElement("ul");for(b=0;b<dext5_admin_lang.grid_color_value.length;b++){var m=dext5_admin_lang.grid_color_value[b];c=dext5_admin_lang.grid_color_text[b];l=document.createElement("li");l.onclick=function(a,b){return function(){document.getElementById("grid_color_value").style.backgroundColor=a;document.getElementById("grid_color_text").innerHTML=b;
document.getElementById("grid_color").value=a;document.getElementById("grid_color_nm").value=b;document.getElementById("grid_color_flag").value="N";document.getElementById("grid_color_list").style.display="none"}}(m,c);h=document.createElement("a");h.className="sebt";h.title=c;var n=document.createElement("span");n.className="cr";n.style.backgroundColor=m;m=document.createElement("span");m.className="crn";m.innerHTML=c;h.appendChild(n);h.appendChild(m);l.appendChild(h);a.appendChild(l)}document.getElementById("grid_color_list").appendChild(a);
c=GetNodeValue(f,"grid_spans");for(b=0;b<dext5_admin_lang.grid_spans.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.grid_spans[b]),a.innerHTML=dext5_admin_lang.grid_spans[b],document.getElementById("grid_spans").appendChild(a),dext5_admin_lang.grid_spans[b]==c&&(a.selected=!0);c=GetNodeValue(f,"grid_form");a=document.createElement("input");a.setAttribute("type","hidden");a.setAttribute("id","grid_form");a.setAttribute("name","grid_form");a.setAttribute("value",
c);e.appendChild(a);for(b=0;b<document.getElementsByName("grid_form_radio").length;b++)document.getElementsByName("grid_form_radio")[b].value==c&&(document.getElementsByName("grid_form_radio")[b].checked=!0);c=GetNodeValue(f,"encoding");for(b=0;b<dext5_admin_lang.encoding_value.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.encoding_value[b]),a.innerHTML=dext5_admin_lang.encoding_text[b],document.getElementById("encoding").appendChild(a),dext5_admin_lang.encoding_value[b]==
c&&(a.selected=!0);c=GetNodeValue(f,"doctype");for(b=0;b<dext5_admin_lang.doctype_value.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.doctype_value[b]),a.innerHTML=dext5_admin_lang.doctype_text[b],document.getElementById("doctype").appendChild(a),dext5_admin_lang.doctype_value[b]==c&&(a.selected=!0);b=GetNodeValue(f,"xmlnsname");document.getElementById("xmlnsname").value=b;c=GetNodeValue(f,"doc_lang");for(b=0;b<dext5_admin_lang.doc_lang.length;b++)a=document.createElement("option"),
a.setAttribute("value",dext5_admin_lang.doc_lang[b]),a.innerHTML=dext5_admin_lang.doc_lang[b],document.getElementById("doc_lang").appendChild(a),dext5_admin_lang.doc_lang[b]==c&&(a.selected=!0);c=GetNodeValue(f,"lang");for(b=0;b<document.getElementById("lang").length;b++)document.getElementById("lang").options[b].value==c&&(document.getElementById("lang").options[b].selected=!0);b=GetNodeValue(f,"width");-1<b.indexOf("%")?document.getElementById("width_unit").value="%":document.getElementById("width_unit").value=
"px";document.getElementById("width").value=parseInt(b,10);b=GetNodeValue(f,"height");-1<b.indexOf("%")?document.getElementById("height_unit").value="%":document.getElementById("height_unit").value="px";document.getElementById("height").value=parseInt(b,10);c=GetNodeValue(f,"skinname");a=document.createElement("input");a.setAttribute("type","hidden");a.setAttribute("id","skinname");a.setAttribute("name","skinname");""==c?a.setAttribute("value","blue"):a.setAttribute("value",c);e.appendChild(a);a=
0;if(""!=c)for(b=0;b<dext5_admin_lang.skinname_value.length;b++)dext5_admin_lang.skinname_text[b].toLowerCase()==c&&(a=b);document.getElementById("skinname_value").style.backgroundColor=dext5_admin_lang.skinname_value[a];document.getElementById("skinname_text").innerHTML=dext5_admin_lang.skinname_text[a];a=document.createElement("ul");for(b=0;b<dext5_admin_lang.skinname_value.length;b++)m=dext5_admin_lang.skinname_value[b],c=dext5_admin_lang.skinname_text[b],l=document.createElement("li"),l.onclick=
function(a,b){return function(){document.getElementById("skinname_value").style.backgroundColor=a;document.getElementById("skinname_text").innerHTML=b;document.getElementById("skinname").value=b.toLowerCase();document.getElementById("skinname_flag").value="N";document.getElementById("skinname_list").style.display="none"}}(m,c),h=document.createElement("a"),h.className="sebt",h.title=c,n=document.createElement("span"),n.className="cr",n.style.backgroundColor=m,m=document.createElement("span"),m.className=
"crn",m.innerHTML=c,h.appendChild(n),h.appendChild(m),l.appendChild(h),a.appendChild(l);document.getElementById("skinname_list").appendChild(a);l=GetNodeValue(f,"font_family");n=GetNode(k,"font_family");c=n.getElementsByTagName("font").length;for(b=0;b<c;b++)h=GetNodeValueIdx(n,"font",b),a=document.createElement("option"),a.setAttribute("value",h),a.innerHTML=h,document.getElementById("setting_font_family").appendChild(a),h==l&&(a.selected=!0);l=GetNodeValue(f,"font_size");n=GetNode(k,"font_size");
c=n.getElementsByTagName("size").length;for(b=0;b<c;b++)h=GetNodeValueIdx(n,"size",b),a=document.createElement("option"),a.setAttribute("value",h),a.innerHTML=h,document.getElementById("setting_font_size").appendChild(a),h==l&&(a.selected=!0);l=GetNodeValue(f,"line_height");h=dext5_admin_lang.line_height;c=h.length;for(b=0;b<c;b++)a=document.createElement("option"),a.setAttribute("value",h[b]),a.innerHTML=h[b],document.getElementById("line_height").appendChild(a),l==h[b]&&(a.selected=!0);b=GetNodeValue(f,
"show_font_real");"1"==b?document.getElementById("show_font_real").value="1":document.getElementById("show_font_real").value="0";c=GetNodeValue(f,"accessibility");for(b=0;b<dext5_admin_lang.accessibility_value.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.accessibility_value[b]),a.innerHTML=dext5_admin_lang.accessibility_text[b],document.getElementById("accessibility").appendChild(a),dext5_admin_lang.accessibility_value[b]==c&&(a.selected=!0);c=GetNodeValue(f,
"topmenu");for(b=0;b<dext5_admin_lang.topmenu_value.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.topmenu_value[b]),a.innerHTML=dext5_admin_lang.topmenu_text[b],document.getElementById("topmenu").appendChild(a),dext5_admin_lang.topmenu_value[b]==c&&(a.selected=!0);c=GetNodeValue(f,"toolbar");for(b=0;b<dext5_admin_lang.toolbar_value.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.toolbar_value[b]),a.innerHTML=dext5_admin_lang.toolbar_text[b],
document.getElementById("toolbar").appendChild(a),dext5_admin_lang.toolbar_value[b]==c&&(a.selected=!0);c=GetNodeValue(f,"statusbar");for(b=0;b<dext5_admin_lang.statusbar_value.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.statusbar_value[b]),a.innerHTML=dext5_admin_lang.statusbar_text[b],document.getElementById("statusbar").appendChild(a),dext5_admin_lang.statusbar_value[b]==c&&(a.selected=!0);c=GetNodeValue(f,"showdialog_pos");for(b=0;b<dext5_admin_lang.showdialog_pos_value.length;b++)a=
document.createElement("option"),a.setAttribute("value",dext5_admin_lang.showdialog_pos_value[b]),a.innerHTML=dext5_admin_lang.showdialog_pos_text[b],document.getElementById("showdialog_pos").appendChild(a),dext5_admin_lang.showdialog_pos_value[b]==c&&(a.selected=!0);b=GetNodeValue(f,"source_viewtype");"1"==b?document.getElementById("source_viewtype").value="1":document.getElementById("source_viewtype").value="0";b=GetNodeValue(f,"user_css_url");""!=b?(document.getElementById("user_css_url").value=
b,document.getElementById("user_css_url").disabled=!1,document.getElementById("chk_user_css_url").checked=!1,document.getElementById("user_css_url_desc").innerHTML=dext5_admin_lang.user_css_url_desc2):(document.getElementById("user_css_url").disabled="disabled",document.getElementById("user_css_url_desc").innerHTML=dext5_admin_lang.user_css_url_desc1);b=GetNodeValue(f,"xhtml_value");"1"==b?document.getElementById("xhtml_value").value=b:document.getElementById("xhtml_value").value="0";b=GetNodeValue(f,
"view_mode_auto_height");"1"==b?document.getElementById("view_mode_auto_height").value=b:document.getElementById("view_mode_auto_height").value="0";b=GetNodeValue(f,"system_title");""!=b&&"error"!=b?document.getElementById("system_title").value=b:document.getElementById("system_title").value="";b=GetNodeValue(f,"table_auto_adjust");"1"==b?document.getElementById("table_auto_adjust").value=b:document.getElementById("table_auto_adjust").value="0"}else f=GetNode(k,"setting"),b=GetNodeValue(f,"grid_color"),
a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","grid_color"),a.setAttribute("name","grid_color"),a.setAttribute("value",b),e.appendChild(a),c=GetNodeValue(f,"grid_color_nm"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","grid_color_nm"),a.setAttribute("name","grid_color_nm"),a.setAttribute("value",c),e.appendChild(a),c=GetNodeValue(f,"grid_spans"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id",
"grid_spans"),a.setAttribute("name","grid_spans"),a.setAttribute("value",c),e.appendChild(a),c=GetNodeValue(f,"grid_form"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","grid_form"),a.setAttribute("name","grid_form"),a.setAttribute("value",c),e.appendChild(a),c=GetNodeValue(f,"encoding"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","encoding"),a.setAttribute("name","encoding"),a.setAttribute("value",c),e.appendChild(a),
c=GetNodeValue(f,"doctype"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","doctype"),a.setAttribute("name","doctype"),a.setAttribute("value",c),e.appendChild(a),b=GetNodeValue(f,"xmlnsname"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","xmlnsname"),a.setAttribute("name","xmlnsname"),a.setAttribute("value",b),e.appendChild(a),c=GetNodeValue(f,"doc_lang"),a=document.createElement("input"),a.setAttribute("type","hidden"),
a.setAttribute("id","doc_lang"),a.setAttribute("name","doc_lang"),a.setAttribute("value",c),e.appendChild(a),c=GetNodeValue(f,"lang"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","lang"),a.setAttribute("name","lang"),a.setAttribute("value",c),e.appendChild(a),b=GetNodeValue(f,"width"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","width"),a.setAttribute("name","width"),a.setAttribute("value",b),e.appendChild(a),b=GetNodeValue(f,
"height"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","height"),a.setAttribute("name","height"),a.setAttribute("value",b),e.appendChild(a),c=GetNodeValue(f,"skinname"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","skinname"),a.setAttribute("name","skinname"),a.setAttribute("value",c),e.appendChild(a),l=GetNodeValue(f,"font_family"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id",
"setting_font_family"),a.setAttribute("name","setting_font_family"),a.setAttribute("value",l),e.appendChild(a),l=GetNodeValue(f,"font_size"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","setting_font_size"),a.setAttribute("name","setting_font_size"),a.setAttribute("value",l),e.appendChild(a),l=GetNodeValue(f,"line_height"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","line_height"),a.setAttribute("name","line_height"),
a.setAttribute("value",l),e.appendChild(a),b=GetNodeValue(f,"show_font_real"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","show_font_real"),a.setAttribute("name","show_font_real"),a.setAttribute("value",b),e.appendChild(a),c=GetNodeValue(f,"accessibility"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","accessibility"),a.setAttribute("name","accessibility"),a.setAttribute("value",c),e.appendChild(a),c=GetNodeValue(f,
"topmenu"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","topmenu"),a.setAttribute("name","topmenu"),a.setAttribute("value",c),e.appendChild(a),"2"==g&&("0"==c?document.getElementById("topmenu_none").checked=!1:"1"==c&&(document.getElementById("topmenu_none").checked=!0,document.getElementById("all_menu").disabled=!0,document.getElementById("set_menu").disabled=!0,document.getElementById("all_right").style.display="none",document.getElementById("right").style.display=
"none",document.getElementById("all_left").style.display="none",document.getElementById("left").style.display="none",document.getElementById("top").style.display="none",document.getElementById("bottom").style.display="none",e.appendChild(a))),c=GetNodeValue(f,"toolbar"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","toolbar"),a.setAttribute("name","toolbar"),a.setAttribute("value",c),e.appendChild(a),"3"==g&&("0"==c?(document.getElementById("toolbar1_none").checked=
!1,document.getElementById("toolbar2_none").checked=!1):"1"==c?(document.getElementById("toolbar1_none").checked=!0,document.getElementById("toolbar2_none").checked=!1,document.getElementById("set_menu1").disabled=!0,document.getElementById("all_right1").style.display="none",document.getElementById("right1").style.display="none",document.getElementById("all_left1").style.display="none",document.getElementById("left1").style.display="none",document.getElementById("top1").style.display="none",document.getElementById("bottom1").style.display=
"none"):"2"==c?(document.getElementById("toolbar1_none").checked=!1,document.getElementById("toolbar2_none").checked=!0,document.getElementById("set_menu2").disabled=!0,document.getElementById("all_right2").style.display="none",document.getElementById("right2").style.display="none",document.getElementById("all_left2").style.display="none",document.getElementById("left2").style.display="none",document.getElementById("top2").style.display="none",document.getElementById("bottom2").style.display="none"):
"3"==c&&(document.getElementById("toolbar1_none").checked=!0,document.getElementById("toolbar2_none").checked=!0,document.getElementById("all_menu").disabled=!0,document.getElementById("set_menu1").disabled=!0,document.getElementById("all_right1").style.display="none",document.getElementById("right1").style.display="none",document.getElementById("all_left1").style.display="none",document.getElementById("left1").style.display="none",document.getElementById("top1").style.display="none",document.getElementById("bottom1").style.display=
"none",document.getElementById("set_menu2").disabled=!0,document.getElementById("all_right2").style.display="none",document.getElementById("right2").style.display="none",document.getElementById("all_left2").style.display="none",document.getElementById("left2").style.display="none",document.getElementById("top2").style.display="none",document.getElementById("bottom2").style.display="none")),c=GetNodeValue(f,"statusbar"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id",
"statusbar"),a.setAttribute("name","statusbar"),a.setAttribute("value",c),e.appendChild(a),"4"==g&&("0"==c?document.getElementById("statusbar_none").checked=!1:"1"==c&&(document.getElementById("statusbar_none").checked=!0,document.getElementById("all_menu").disabled=!0,document.getElementById("set_menu").disabled=!0,document.getElementById("all_right").style.display="none",document.getElementById("right").style.display="none",document.getElementById("all_left").style.display="none",document.getElementById("left").style.display=
"none",document.getElementById("top").style.display="none",document.getElementById("bottom").style.display="none",e.appendChild(a))),c=GetNodeValue(f,"showdialog_pos"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","showdialog_pos"),a.setAttribute("name","showdialog_pos"),a.setAttribute("value",c),e.appendChild(a),b=GetNodeValue(f,"source_viewtype"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","source_viewtype"),a.setAttribute("name",
"source_viewtype"),a.setAttribute("value",b),e.appendChild(a),b=GetNodeValue(f,"user_css_url"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","user_css_url"),a.setAttribute("name","user_css_url"),a.setAttribute("value",b),e.appendChild(a),b=GetNodeValue(f,"xhtml_value"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","xhtml_value"),a.setAttribute("name","xhtml_value"),a.setAttribute("value",b),e.appendChild(a),b=GetNodeValue(f,
"view_mode_auto_height"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","view_mode_auto_height"),a.setAttribute("name","view_mode_auto_height"),a.setAttribute("value",b),e.appendChild(a),b=GetNodeValue(f,"system_title"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","system_title"),a.setAttribute("name","system_title"),a.setAttribute("value",b),e.appendChild(a),b=GetNodeValue(f,"table_auto_adjust"),a=document.createElement("input"),
a.setAttribute("type","hidden"),a.setAttribute("id","table_auto_adjust"),a.setAttribute("name","table_auto_adjust"),a.setAttribute("value",b),e.appendChild(a);if("9"==g){f=GetNode(k,"uploader_setting");c=GetNodeValue(f,"develop_langage");for(b=0;b<dext5_admin_lang.develop_langage.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.develop_langage[b]),a.innerHTML=dext5_admin_lang.develop_langage[b],document.getElementById("develop_langage").appendChild(a),dext5_admin_lang.develop_langage[b]==
c&&(a.selected=!0);b=GetNodeValue(f,"handler_url");""==b?(document.getElementById("chk_handler_url").checked="checked",document.getElementById("handler_url").disabled="disabled",document.getElementById("span_desc").innerHTML=dext5_admin_lang.upload_url_desc1):(document.getElementById("chk_handler_url").checked=!1,document.getElementById("handler_url").disabled=!1,document.getElementById("span_desc").innerHTML=dext5_admin_lang.upload_url_desc2);document.getElementById("handler_url").value=b;a=GetNodeValue(f,
"server_domain");""==a?(document.getElementById("chk_server_domain").checked="checked",document.getElementById("server_domain").disabled="disabled",document.getElementById("span_desc3").innerHTML=dext5_admin_lang.server_domain_desc1):(document.getElementById("chk_server_domain").checked=!1,document.getElementById("server_domain").disabled=!1,document.getElementById("span_desc3").innerHTML=dext5_admin_lang.server_domain_desc2);document.getElementById("server_domain").value=a;b=GetNodeValue(f,"to_save_path_url");
""==b?(document.getElementById("chk_to_save_path_url").checked="checked",document.getElementById("to_save_path_url").disabled="disabled",document.getElementById("span_desc2").innerHTML=dext5_admin_lang.save_path_desc1):(document.getElementById("chk_to_save_path_url").checked=!1,document.getElementById("to_save_path_url").disabled=!1,document.getElementById("span_desc2").innerHTML=dext5_admin_lang.save_path_desc2);document.getElementById("to_save_path_url").value=b;c=GetNodeValue(f,"save_foldername_rule");
for(b=0;b<dext5_admin_lang.save_foldername_rule.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.save_foldername_rule[b]),a.innerHTML=""==dext5_admin_lang.save_foldername_rule[b]?"None":dext5_admin_lang.save_foldername_rule[b],document.getElementById("save_foldername_rule").appendChild(a),dext5_admin_lang.save_foldername_rule[b]==c&&(a.selected=!0);c=GetNodeValue(f,"save_filename_rule");for(b=0;b<dext5_admin_lang.save_filename_rule.length;b++)a=document.createElement("option"),
a.setAttribute("value",dext5_admin_lang.save_filename_rule[b]),a.innerHTML=""==dext5_admin_lang.save_filename_rule[b]?"None":dext5_admin_lang.save_filename_rule[b],document.getElementById("save_filename_rule").appendChild(a),dext5_admin_lang.save_filename_rule[b]==c&&(a.selected=!0);c=GetNodeValue(f,"image_convert_format");for(b=0;b<dext5_admin_lang.image_convert_format.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.image_convert_format[b]),a.innerHTML=""==dext5_admin_lang.image_convert_format[b]?
"None":dext5_admin_lang.image_convert_format[b],document.getElementById("image_convert_format").appendChild(a),dext5_admin_lang.image_convert_format[b]==c&&(a.selected=!0);b=GetNodeValue(f,"image_convert_width");document.getElementById("image_convert_width").value=b;b=GetNodeValue(f,"image_convert_height");document.getElementById("image_convert_height").value=b;b=GetNodeValue(f,"image_auto_fit");"1"==b?document.getElementById("image_auto_fit").value=b:document.getElementById("image_auto_fit").value=
"0"}else f=GetNode(k,"uploader_setting"),c=GetNodeValue(f,"develop_langage"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","develop_langage"),a.setAttribute("name","develop_langage"),a.setAttribute("value",c),e.appendChild(a),b=GetNodeValue(f,"handler_url"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","handler_url"),a.setAttribute("name","handler_url"),a.setAttribute("value",b),e.appendChild(a),b=GetNodeValue(f,"to_save_path_url"),
a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","to_save_path_url"),a.setAttribute("name","to_save_path_url"),a.setAttribute("value",b),e.appendChild(a),c=GetNodeValue(f,"save_foldername_rule"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","save_foldername_rule"),a.setAttribute("name","save_foldername_rule"),a.setAttribute("value",c),e.appendChild(a),c=GetNodeValue(f,"save_filename_rule"),a=document.createElement("input"),
a.setAttribute("type","hidden"),a.setAttribute("id","save_filename_rule"),a.setAttribute("name","save_filename_rule"),a.setAttribute("value",c),e.appendChild(a),c=GetNodeValue(f,"image_convert_format"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","image_convert_format"),a.setAttribute("name","image_convert_format"),a.setAttribute("value",c),e.appendChild(a),b=GetNodeValue(f,"image_convert_width"),a=document.createElement("input"),a.setAttribute("type","hidden"),
a.setAttribute("id","image_convert_width"),a.setAttribute("name","image_convert_width"),a.setAttribute("value",b),e.appendChild(a),b=GetNodeValue(f,"image_convert_height"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","image_convert_height"),a.setAttribute("name","image_convert_height"),a.setAttribute("value",b),e.appendChild(a),b=GetNodeValue(f,"image_auto_fit"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","image_auto_fit"),
a.setAttribute("name","image_auto_fit"),a.setAttribute("value",b),e.appendChild(a);if("10"==g){k=GetNode(k,"xss_protection");b=GetNodeValue(k,"xss_use");"1"==b?document.getElementById("xss_use").value="1":document.getElementById("xss_use").value="0";b=GetNodeValue(k,"xss_remove_tags");if(""!=b)for(e=b.split(","),b=0;b<e.length;b++)a=document.createElement("option"),a.value=e[b],a.innerHTML=e[b],document.getElementById("set_remove_tag").appendChild(a);k=GetNodeValue(k,"xss_remove_events");if(""!=k)if("all"==
k)document.getElementById("chk_all_remove").checked=!0,check_event_all(!0);else for(e=k.split(","),b=0;b<e.length;b++)a=document.createElement("option"),a.value=e[b],a.innerHTML=e[b],document.getElementById("set_remove_event").appendChild(a)}else k=GetNode(k,"xss_protection"),b=GetNodeValue(k,"xss_use"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","xss_use"),a.setAttribute("name","xss_use"),a.setAttribute("value",b),e.appendChild(a),b=GetNodeValue(k,"xss_remove_tags"),
a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","xss_remove_tags"),a.setAttribute("name","xss_remove_tags"),a.setAttribute("value",b),e.appendChild(a),k=GetNodeValue(k,"xss_remove_events"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","xss_remove_events"),a.setAttribute("name","xss_remove_events"),a.setAttribute("value",k),e.appendChild(a)}
function move_all_option(d,g,e){for(var a=[],c=0;c<d.length;c++){if("design"!=d.options[c].value){a.push(d.options[c]);var k=document.createElement("option");k.value=d.options[c].value;k.innerHTML=d.options[c].innerHTML;g.appendChild(k)}if(c==d.length-1)for(k=0;k<a.length;k++)a[k].value!=e&&d.removeChild(a[k])}}
function move_option(d,g,e){for(var a=[],c=0;c<d.length;c++){if(1==d.options[c].selected){var k=document.createElement("option");k.value=d.options[c].value;k.innerHTML=d.options[c].innerHTML;g.appendChild(k);a.push(d.options[c])}if(c==d.length-1)for(k=0;k<a.length;k++)a[k].value!=e&&d.removeChild(a[k])}}
function upExcute(d){for(var g=d.length,e=[],a=0;a<g;a++)if(1==d.options[a].selected&&(e.push(d.options[a]),0<=a-1&&e[0]!=d.options[0])){var c=d.options[a-1].value,k=d.options[a-1].innerHTML;d.options[a-1].value=d.options[a].value;d.options[a-1].innerHTML=d.options[a].innerHTML;d.options[a].value=c;d.options[a].innerHTML=k;d.options[a-1].selected=!0;d.options[a].selected=!1}}
function bottomExcute(d){for(var g=d.length,e=[],a=g-1;0<=a;a--)1==d.options[a].selected&&e.push(d.options[a]);for(a=g-1;0<=a&&e[0]!=d.options[g-1];a--)if(1==d.options[a].selected&&a+1<=g-1){var c=d.options[a+1].value,k=d.options[a+1].innerHTML;d.options[a+1].value=d.options[a].value;d.options[a+1].innerHTML=d.options[a].innerHTML;d.options[a].value=c;d.options[a].innerHTML=k;d.options[a+1].selected=!0;d.options[a].selected=!1}}
function setCookieSave(d,g,e){var a=new Date;a.setDate(a.getDate()+e);document.cookie=d+"="+escape(g)+"; path=/; expires="+a.toGMTString()+";"}function getLoginCookei(){var d=document.cookie+";",g=d.indexOf("id",0),e="";-1!=g&&(d=d.substring(g,d.length),begin=d.indexOf("=",0)+1,end=d.indexOf(";",begin),e=unescape(d.substring(begin,end)));""!=e&&(document.getElementById("id").value=e,document.getElementById("id_check").checked=!0)}
var Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(d){var g="",e,a,c,k,f,b,l=0;for(d=Base64._utf8_encode(d);l<d.length;)e=d.charCodeAt(l++),a=d.charCodeAt(l++),c=d.charCodeAt(l++),k=e>>2,e=(e&3)<<4|a>>4,f=(a&15)<<2|c>>6,b=c&63,isNaN(a)?f=b=64:isNaN(c)&&(b=64),g=g+this._keyStr.charAt(k)+this._keyStr.charAt(e)+this._keyStr.charAt(f)+this._keyStr.charAt(b);return g},decode:function(d){var g="",e,a,c,k,f,b=0;for(d=d.replace(/[^A-Za-z0-9\+\/\=]/g,"");b<
d.length;)e=this._keyStr.indexOf(d.charAt(b++)),a=this._keyStr.indexOf(d.charAt(b++)),k=this._keyStr.indexOf(d.charAt(b++)),f=this._keyStr.indexOf(d.charAt(b++)),e=e<<2|a>>4,a=(a&15)<<4|k>>2,c=(k&3)<<6|f,g+=String.fromCharCode(e),64!=k&&(g+=String.fromCharCode(a)),64!=f&&(g+=String.fromCharCode(c));return g=Base64._utf8_decode(g)},_utf8_encode:function(d){d=d.replace(/\r\n/g,"\n");for(var g="",e=0;e<d.length;e++){var a=d.charCodeAt(e);128>a?g+=String.fromCharCode(a):(127<a&&2048>a?g+=String.fromCharCode(a>>
6|192):(g+=String.fromCharCode(a>>12|224),g+=String.fromCharCode(a>>6&63|128)),g+=String.fromCharCode(a&63|128))}return g},_utf8_decode:function(d){for(var g="",e=0,a=c1=c2=0;e<d.length;)a=d.charCodeAt(e),128>a?(g+=String.fromCharCode(a),e++):191<a&&224>a?(c2=d.charCodeAt(e+1),g+=String.fromCharCode((a&31)<<6|c2&63),e+=2):(c2=d.charCodeAt(e+1),c3=d.charCodeAt(e+2),g+=String.fromCharCode((a&15)<<12|(c2&63)<<6|c3&63),e+=3);return g},URLEncode:function(d){return escape(this._utf8_encode(d))},URLDecode:function(d){return this._utf8_decode(unescape(d))}};
function templeteConfigSet(d){xmlhttpPostXML(d,"","xmlTempleteConfig","")}var templete_array=[];
function xmlTempleteConfig(d,g){if(null==d)alert("\ufffd\u0537\ufffd\ufffd\u03fd\ufffd \ufffd\ufffd\ufffd\u00f8\ufffd Config \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\u03bf\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\u02bd\ufffd\ufffd\u03f4\ufffd."),document.getElementById("prev_config_path").focus();else{var e=GetNode(d,"dext5"),a=document.getElementById("ul_class"),c=document.getElementById("ul_templete");a.innerHTML="";c.innerHTML=
"";for(var c=e.getElementsByTagName("FormList").length,k=0;k<c;k++){var f=GetNodeIdx(e,"FormList",k),b=f.getAttribute("Name"),l=document.createElement("li");l.setAttribute("onclick","javascript:classClick("+k+")");var h=document.createElement("span"),m=document.createElement("img");m.setAttribute("src","../../../images/editor/dialog/close_folder.gif");m.setAttribute("alt","\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd");h.appendChild(m);l.appendChild(h);h=document.createElement("span");
h.innerHTML="&nbsp;";l.appendChild(h);h=document.createElement("span");h.setAttribute("class","li_title");h.innerHTML=b;l.appendChild(h);h=document.createElement("span");h.innerHTML="&nbsp;";l.appendChild(h);h=document.createElement("img");h.setAttribute("src","../../../images/admin/s_btn_modify.png");h.setAttribute("style","cursor:pointer;");h.setAttribute("alt","\ufffd\ufffd\ufffd\ufffd");h.setAttribute("onclick","javascript:classModify("+k+")");l.appendChild(h);h=document.createElement("span");
h.innerHTML="&nbsp;";l.appendChild(h);h=document.createElement("img");h.setAttribute("src","../../../images/admin/s_btn_delete.png");h.setAttribute("style","cursor:pointer;");h.setAttribute("alt","\ufffd\ufffd\ufffd\ufffd");h.setAttribute("onclick","javascript:classDelete("+k+")");l.appendChild(h);h=document.createElement("span");h.innerHTML="&nbsp;";l.appendChild(h);h=document.createElement("img");h.setAttribute("src","../../../images/admin/s_btn_up.png");h.setAttribute("style","cursor:pointer;");
h.setAttribute("alt","\ufffd\ufffd\ufffd\ufffd");h.setAttribute("onclick","javascript:classUp("+k+")");l.appendChild(h);h=document.createElement("span");h.innerHTML="&nbsp;";l.appendChild(h);h=document.createElement("img");h.setAttribute("src","../../../images/admin/s_btn_down.png");h.setAttribute("style","cursor:pointer;");h.setAttribute("alt","\ufffd\u01b7\ufffd\ufffd\ufffd");h.setAttribute("onclick","javascript:classDown("+k+")");l.appendChild(h);h=document.createElement("input");h.setAttribute("type",
"hidden");h.setAttribute("name","class[]");h.setAttribute("value",b);l.appendChild(h);b=document.createElement("input");b.setAttribute("type","hidden");b.setAttribute("value","0");l.appendChild(b);a.appendChild(l);l=f.getElementsByTagName("FORM").length;templete_array[k]="";for(b=0;b<l;b++)m=GetNodeIdx(f,"FORM",b),h=m.getAttribute("FormName"),m=m.getAttribute("url"),templete_array[k]+=h+"\f"+m,b!=l-1&&(templete_array[k]+="\x0B")}templeteAreaSet()}}
function templeteAreaSet(){var d=document.getElementById("ul_templete");d.innerHTML="";for(var g=templete_array.length,e=0;e<g;e++)if(""!=templete_array[e])for(var a=templete_array[e].split("\x0B"),c=a.length,k=0;k<c;k++){var f=a[k].split("\f"),b=f[0],l=f[1],f=document.createElement("li");f.setAttribute("id","templete_"+e);f.style.display="none";var h=document.createElement("span"),m=document.createElement("img");m.setAttribute("src","../../../images/editor/dialog/file.gif");m.setAttribute("alt",
"\ufffd\ufffd\ufffd\u03fe\ufffd\ufffd\ufffd\ufffd\ufffd");h.appendChild(m);f.appendChild(h);h=document.createElement("span");h.innerHTML="&nbsp;";f.appendChild(h);h=document.createElement("span");h.setAttribute("class","li_title");h.innerHTML=b;f.appendChild(h);h=document.createElement("span");h.innerHTML="&nbsp;";f.appendChild(h);h=document.createElement("img");h.setAttribute("src","../../../images/admin/s_btn_modify.png");h.setAttribute("style","cursor:pointer;");h.setAttribute("onclick","javascript:templeteModify("+
e+","+k+")");h.setAttribute("alt","\ufffd\ufffd\ufffd\ufffd");f.appendChild(h);h=document.createElement("span");h.innerHTML="&nbsp;";f.appendChild(h);h=document.createElement("img");h.setAttribute("src","../../../images/admin/s_btn_delete.png");h.setAttribute("style","cursor:pointer;");h.setAttribute("onclick","javascript:templeteDelete("+e+","+k+")");h.setAttribute("alt","\ufffd\ufffd\ufffd\ufffd");f.appendChild(h);h=document.createElement("span");h.innerHTML="&nbsp;";f.appendChild(h);h=document.createElement("img");
h.setAttribute("src","../../../images/admin/s_btn_up.png");h.setAttribute("style","cursor:pointer;");h.setAttribute("onclick","javascript:templeteUp("+e+","+k+")");h.setAttribute("alt","\ufffd\ufffd\ufffd\ufffd");f.appendChild(h);h=document.createElement("span");h.innerHTML="&nbsp;";f.appendChild(h);h=document.createElement("img");h.setAttribute("src","../../../images/admin/s_btn_down.png");h.setAttribute("style","cursor:pointer;");h.setAttribute("onclick","javascript:templeteDown("+e+","+k+")");
h.setAttribute("alt","\ufffd\u01b7\ufffd\ufffd\ufffd");f.appendChild(h);h=document.createElement("input");h.setAttribute("type","hidden");h.setAttribute("name","templete_name_"+e+"[]");h.setAttribute("value",b);f.appendChild(h);b=document.createElement("input");b.setAttribute("type","hidden");b.setAttribute("name","templete_url_"+e+"[]");b.setAttribute("value",l);f.appendChild(b);b=document.createElement("input");b.setAttribute("type","hidden");b.setAttribute("value","0");f.appendChild(b);d.appendChild(f)}}
function classClick(d){if("0"==document.getElementById("selected_class_none").value){templeteModifyClear();document.getElementById("selected_class").value=d;for(var g=document.getElementById("ul_class"),e=document.getElementById("ul_templete"),a=g.childNodes.length,c=0;c<a;c++)g.childNodes[c].className="",g.childNodes[c].childNodes[0].childNodes[0].src="../../../images/editor/dialog/close_folder.gif";g.childNodes[d].className="on";g.childNodes[d].childNodes[0].childNodes[0].src="../../../images/editor/dialog/open_folder.gif";
g=e.childNodes.length;for(c=0;c<g;c++)e.childNodes[c].style.display="none";for(c=0;c<g;c++)e.childNodes[c].id=="templete_"+d&&(e.childNodes[c].style.display="")}else document.getElementById("selected_class_none").value="0"}
function classAdd(d){if(""==d.value)alert("\ufffd\u07f0\ufffd\ufffd\u03f7\ufffd\ufffd\ufffd \u016c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\u0537\ufffd\ufffd\ufffd\ufffd\u05bc\ufffd\ufffd\ufffd."),d.focus();else if(confirm("\u016c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\u07f0\ufffd\ufffd\u03fd\u00f0\u06bd\ufffd\ufffd\u03f1\ufffd?")){classModifyClear();templeteModifyClear();var g=document.getElementById("ul_class"),e=g.childNodes.length,a=document.createElement("li");a.setAttribute("onclick",
"javascript:classClick("+e+")");var c=document.createElement("span"),k=document.createElement("img");k.setAttribute("src","../../../images/editor/dialog/close_folder.gif");k.setAttribute("alt","\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd");c.appendChild(k);a.appendChild(c);c=document.createElement("span");c.innerHTML="&nbsp;";a.appendChild(c);c=document.createElement("span");c.setAttribute("class","li_title");c.innerHTML=d.value;a.appendChild(c);c=document.createElement("span");c.innerHTML=
"&nbsp;";a.appendChild(c);c=document.createElement("img");c.setAttribute("src","../../../images/admin/s_btn_modify.png");c.setAttribute("style","cursor:pointer;");c.setAttribute("alt","\ufffd\ufffd\ufffd\ufffd");c.setAttribute("onclick","javascript:classModify("+e+")");a.appendChild(c);c=document.createElement("span");c.innerHTML="&nbsp;";a.appendChild(c);c=document.createElement("img");c.setAttribute("src","../../../images/admin/s_btn_delete.png");c.setAttribute("style","cursor:pointer;");c.setAttribute("alt",
"\ufffd\ufffd\ufffd\ufffd");c.setAttribute("onclick","javascript:classDelete("+e+")");a.appendChild(c);c=document.createElement("span");c.innerHTML="&nbsp;";a.appendChild(c);c=document.createElement("img");c.setAttribute("src","../../../images/admin/s_btn_up.png");c.setAttribute("style","cursor:pointer;");c.setAttribute("alt","\ufffd\ufffd\ufffd\ufffd");c.setAttribute("onclick","javascript:classUp("+e+")");a.appendChild(c);c=document.createElement("span");c.innerHTML="&nbsp;";a.appendChild(c);c=document.createElement("img");
c.setAttribute("src","../../../images/admin/s_btn_down.png");c.setAttribute("style","cursor:pointer;");c.setAttribute("alt","\ufffd\u01b7\ufffd\ufffd\ufffd");c.setAttribute("onclick","javascript:classDown("+e+")");a.appendChild(c);c=document.createElement("input");c.setAttribute("type","hidden");c.setAttribute("name","class[]");c.setAttribute("value",d.value);a.appendChild(c);c=document.createElement("input");c.setAttribute("type","hidden");c.setAttribute("value","0");a.appendChild(c);g.appendChild(a);
d.value="";templete_array[e]=""}}
function classModify(d){templeteModifyClear();document.getElementById("selected_class_none").value="1";var g=document.getElementById("ul_class");if("0"==g.childNodes[d].childNodes[12].value)classModifyClear(),g.childNodes[d].childNodes[2].innerHTML='<input type="text" id="class_text_'+d+'" name="class_text_'+d+'" style="width:100%" value="'+g.childNodes[d].childNodes[2].innerHTML+'"/>',g.childNodes[d].childNodes[12].value="1";else{var e=g.childNodes[d].childNodes[2].childNodes[0].value;""==e?(alert("\ufffd\ufffd\ufffd\ufffd\ufffd\u03f7\ufffd\ufffd\ufffd \u016c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\u0537\ufffd\ufffd\ufffd\ufffd\u05bc\ufffd\ufffd\ufffd."),
g.childNodes[d].childNodes[2].childNodes[0].focus()):confirm("\ufffd\ufffd\ufffd\ufffd\ufffd\u03fd\u00f0\u06bd\ufffd\ufffd\u03f1\ufffd?")&&(g.childNodes[d].childNodes[2].innerHTML=e,g.childNodes[d].childNodes[11].value=e,g.childNodes[d].childNodes[12].value="0")}}
function classDelete(d){classModifyClear();templeteModifyClear();document.getElementById("selected_class_none").value="1";if(confirm("\ufffd\ufffd\ufffd\ufffd\ufffd\u03fd\u00f8\ufffd\n\u016c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\u0535\ufffd \ufffd\ufffd\ufffd\u00f8\ufffd\ufffd\ufffd\ufffd \ufffd\u0634\ufffd \ufffd\ufffd\ufffd\u03f5\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\u02f4\u03f4\ufffd.\n\n\ufffd\u05f7\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\u03fd\u00f0\u06bd\ufffd\ufffd\u03f1\ufffd?")){for(var g=templete_array.length,
e=d;e<g;e++){if(e==d){var a=templete_array[e],c=document.all.dext5;document.getElementById("mode").value="DELETE_ALL";document.getElementById("delete_url").value=a;c.submit()}else templete_array[e-1]=templete_array[e];e==g-1&&templete_array.pop()}templeteAreaSet();g=document.getElementById("ul_class");a=g.childNodes.length;for(e=d+1;e<a;e++)g.childNodes[e].setAttribute("onclick","javascript:classClick("+(e-1)+")"),g.childNodes[e].childNodes[4].setAttribute("onclick","javascript:classModify("+(e-1)+
")"),g.childNodes[e].childNodes[6].setAttribute("onclick","javascript:classDelete("+(e-1)+")"),g.childNodes[e].childNodes[8].setAttribute("onclick","javascript:classUp("+(e-1)+")"),g.childNodes[e].childNodes[10].setAttribute("onclick","javascript:classDown("+(e-1)+")");g.removeChild(g.childNodes[d])}}
function classUp(d){if(0<d){classModifyClear();templeteModifyClear();var g=document.getElementById("ul_class"),e=g.childNodes[d].childNodes[2].innerHTML,a=g.childNodes[d].childNodes[11].value;g.childNodes[d].childNodes[2].innerHTML=g.childNodes[d-1].childNodes[2].innerHTML;g.childNodes[d].childNodes[11].value=g.childNodes[d-1].childNodes[11].value;g.childNodes[d-1].childNodes[2].innerHTML=e;g.childNodes[d-1].childNodes[11].value=a;e=g.childNodes.length;for(a=0;a<e;a++)g.childNodes[a].className="",
g.childNodes[a].childNodes[0].childNodes[0].src="../../../images/editor/dialog/close_folder.gif";g.childNodes[d-1].className="on";g.childNodes[d-1].childNodes[0].childNodes[0].src="../../../images/editor/dialog/open_folder.gif";g=templete_array[d];templete_array[d]=templete_array[d-1];templete_array[d-1]=g;templeteAreaSet();classClick(d-1);document.getElementById("selected_class_none").value="1"}}
function classDown(d){if(d<templete_array.length-1){classModifyClear();templeteModifyClear();var g=document.getElementById("ul_class"),e=g.childNodes[d].childNodes[2].innerHTML,a=g.childNodes[d].childNodes[11].value;g.childNodes[d].childNodes[2].innerHTML=g.childNodes[d+1].childNodes[2].innerHTML;g.childNodes[d].childNodes[11].value=g.childNodes[d+1].childNodes[11].value;g.childNodes[d+1].childNodes[2].innerHTML=e;g.childNodes[d+1].childNodes[11].value=a;e=g.childNodes.length;for(a=0;a<e;a++)g.childNodes[a].className=
"",g.childNodes[a].childNodes[0].childNodes[0].src="../../../images/editor/dialog/close_folder.gif";g.childNodes[d+1].className="on";g.childNodes[d+1].childNodes[0].childNodes[0].src="../../../images/editor/dialog/open_folder.gif";g=templete_array[d];templete_array[d]=templete_array[d+1];templete_array[d+1]=g;templeteAreaSet();classClick(d+1);document.getElementById("selected_class_none").value="1"}}
function classModifyClear(){for(var d=document.getElementById("ul_class"),g=d.childNodes.length,e=0;e<g;e++)d.childNodes[e].childNodes[2].childNodes[0].tagName&&"input"==d.childNodes[e].childNodes[2].childNodes[0].tagName.toLowerCase()&&(d.childNodes[e].childNodes[2].innerHTML=d.childNodes[e].childNodes[2].childNodes[0].value,d.childNodes[e].childNodes[12].value="0")}
function templeteAddConfirm(){var d=document.getElementById("templete_name"),g=document.getElementById("load_templete"),e=document.getElementById("selected_class"),a=document.getElementById("ul_class");if(""==e.value)return alert("\u016c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05bc\ufffd\ufffd\ufffd."),a.focus(),!1;if(""==g.value)return alert("\ufffd\u07f0\ufffd\ufffd\u03f7\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\u00f8\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05bc\ufffd\ufffd\ufffd."),
g.focus(),!1;if(""==d.value)return alert("\ufffd\u07f0\ufffd\ufffd\u03f7\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\u00f8\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\u0537\ufffd\ufffd\ufffd\ufffd\u05bc\ufffd\ufffd\ufffd."),d.focus(),!1;a=g.value.slice(g.value.indexOf(".")+1).toLowerCase();if("html"!=a&&"htm"!=a)return alert("html \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05bc\ufffd\ufffd\ufffd"),g.focus(),!1;if(confirm("\ufffd\ufffd\ufffd\u00f8\ufffd\ufffd\ufffd \ufffd\u07f0\ufffd\ufffd\u03fd\u00f0\u06bd\ufffd\ufffd\u03f1\ufffd?"))g=
document.all.dext5,document.getElementById("mode").value="ADD",document.getElementById("guid").value=getGuid(),g.submit(),g=d.value,a="pages/forms/"+document.getElementById("guid").value+".html",templete_array[e.value]=""==templete_array[e.value]?g+"\f"+a:templete_array[e.value]+"\x0B"+g+"\f"+a,d.value="",templeteAreaSet(),classClick(e.value);else return!1}
function templeteModify(d,g){classModifyClear();for(var e=0,a=0;a<d;a++)if(""!=templete_array[a])var c=templete_array[a].split("\x0B"),e=e+c.length;a=document.getElementById("ul_templete");if("0"==a.childNodes[e+g].childNodes[13].value)templeteModifyClear(),a.childNodes[e+g].childNodes[2].innerHTML='<input type="text" style="width:100%" value="'+a.childNodes[e+g].childNodes[2].innerHTML+'"/>',a.childNodes[e+g].childNodes[13].value="1";else{var k=a.childNodes[e+g].childNodes[2].childNodes[0].value;
if(""==k)alert("\ufffd\ufffd\ufffd\ufffd\ufffd\u03f7\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\u00f8\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\u0537\ufffd\ufffd\ufffd\ufffd\u05bc\ufffd\ufffd\ufffd."),a.childNodes[e+g].childNodes[2].childNodes[0].focus();else if(confirm("\ufffd\ufffd\ufffd\ufffd\ufffd\u03fd\u00f0\u06bd\ufffd\ufffd\u03f1\ufffd?")){for(var c=templete_array[d].split("\x0B"),e=c.length,f="",a=0;a<e;a++){if(a==g)var b=c[a].split("\f"),f=f+(k+"\f"+b[1]);else f+=c[a];a!=e-1&&(f+="\x0B")}templete_array[d]=
f;templeteAreaSet();classClick(d)}}}
function templeteDelete(d,g){classModifyClear();templeteModifyClear();if(confirm("\ufffd\ufffd\ufffd\ufffd\ufffd\u03fd\u00f8\ufffd \ufffd\ufffd\ufffd\u00f8\ufffd\ufffd\ufffd \ufffd\u0634\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\u02f4\u03f4\ufffd.\n\ufffd\u05f7\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\u03fd\u00f0\u06bd\ufffd\ufffd\u03f1\ufffd?")){for(var e="",a="",c=templete_array[d].split("\x0B"),k=c.length,f=0;f<k;f++)g==f?e=c[f].split("\f")[1]:(a+=c[f],g==
k-1?f!=k-2&&(a+="\x0B"):g!=k-1&&f!=k-1&&(a+="\x0B"));c=document.all.dext5;document.getElementById("mode").value="DELETE";document.getElementById("delete_url").value=e;c.submit();templete_array[d]=a;templeteAreaSet();classClick(d)}}
function templeteUp(d,g){if(0<g){classModifyClear();templeteModifyClear();var e=templete_array[d].split("\x0B"),a=e.length,c=e[g];e[g]=e[g-1];e[g-1]=c;templete_array[d]="";for(c=0;c<a;c++)templete_array[d]+=e[c],c!=a-1&&(templete_array[d]+="\x0B");templeteAreaSet();classClick(d)}}
function templeteDown(d,g){var e=templete_array[d].split("\x0B"),a=e.length;if(g<a-1){classModifyClear();templeteModifyClear();var e=templete_array[d].split("\x0B"),a=e.length,c=e[g];e[g]=e[g+1];e[g+1]=c;templete_array[d]="";for(c=0;c<a;c++)templete_array[d]+=e[c],c!=a-1&&(templete_array[d]+="\x0B");templeteAreaSet();classClick(d)}}
function templeteModifyClear(){for(var d=document.getElementById("ul_templete"),g=d.childNodes.length,e=0;e<g;e++)d.childNodes[e].childNodes[2].childNodes[0].tagName&&"input"==d.childNodes[e].childNodes[2].childNodes[0].tagName.toLowerCase()&&(d.childNodes[e].childNodes[2].innerHTML=d.childNodes[e].childNodes[2].childNodes[0].value,d.childNodes[e].childNodes[13].value="0")}
function getGuid(){var d=0,g=(new Date).getTime().toString(32),e;for(e=0;5>e;e++)g+=Math.floor(65535*Math.random()).toString(32);return g+(d++).toString(32)};
