var language = {
	KOR : {
		message_more_back : "뒤로 버튼을 한번 더 누르시면 종료됩니다.",
	    message_dont_open_file : "다운로드가 완료되었습니다. 상단에 상태표시줄에서 파일을 열수 있습니다.",
	    service_exception_expired_login_key : "인증이 만료되었습니다.",
	    service_exception_invalid_login_key : "인증키가 유효하지 않습니다.",
	    service_exception_service : "서버에 문제가 발생했습니다.",
	    service_exception_io : "통신에 문제가 있습니다.",
	    service_exception_etc : "에러가 발생했습니다.",
	    warn_empty_message : "검색된 데이터가 없습니다.",
	    warn_input_message : "검색어를 입력해 주세요.",
	    signin : "Sign in",
	    login : "로그인",
	    simple_login : "간편 로그인",
	    general_login : "일반 로그인",
	    news : "메인",
	    work : "워크 다이어리",
	    mail : "메일",
	    approval : "결재",
	    board : "게시판",
	    organ : "조직도",
	    resource : "자원예약",
	    time : "근태관리",
	    goout : "외출사유 입력",
	    gqms : "G-QMS",
	    home_news : "메인",
	    home_work : "워크 다이어리",
	    home_mail : "전자메일",
	    home_approval : "전자결재",
	    home_board : "게시판",
	    home_organ : "조직도",
	    home_resource : "자원예약",
	    unread : "읽지않음",
	    flagged : "플래그 지정됨",
	    today_mails : "오늘 메일",
	    close : "닫기",
	    ok : "확인",
	    save : "저장",
	    yes : "예",
	    no : "아니오",
	    add : "추가",
	    apply : "적용",
	    choice : "선택",
	    write_mail : "메일 작성하기",
	    view_mail : "메일 보기",
	    send : "보내기",
	    attach : "첨부",
	    reply : "회신",
	    forward : "전달",
	    move_message : "메일 이동",
	    move_message_abbr : "이동",
	    set_flag : "깃발 표시",
	    set_flag_abbr : "표시",
	    clear_flag : "깃발 해제",
	    set_read : "읽음으로 표시",
	    set_unread : "읽지않음으로 표시",
	    bookmark : "즐겨찾기",
	    search : "검색",
	    find : "조회",
	    edit : "편집",
	    remove : "삭제",
	    cancel : "취소",
	    modify : "수정",
	    option : "옵션",
	    remove_message : "삭제하시겠습니까?",
	    set_flag_message : "깃발 등록되었습니다.",
	    clear_flag_message : "깃발 해지되었습니다.",
	    prev : "이전",
	    next : "다음",
	    from_address_ : "보낸 사람:",
	    to_address_ : "받는 사람:",
	    cc_address_ : "참조:",
	    bcc_address_ : "숨은 참조:",
	    from_address : "보낸 사람:",
	    to_address : "받는 사람",
	    cc_address : "참조",
	    bcc_address : "숨은 참조",
	    attach_files : "첨부파일",
	    to_detail : "자세히",
	    view_detail : "자세히 보기",
	    view_summary : "간단히 보기",
	    mail_write : "메일 작성",
	    me_address : "내게 쓰기",
	    all : "전체",
	    subject : "제목",
	    body : "본문",
	    sender : "발신자",
	    receive : "수신자",
	    subjectbody : "제목+본문",
	    reg_user_name : "작성자",
	    reg_date : "작성일",
	    search_hint : "검색어를 입력하세요.",
	    subject_hint : "제목을 입력하세요.",
	    receive_hint : "수신자를 입력하세요.",
	    selected_message : " 개 선택됨",
	    more_view : "더보기",
	    content_hint : "내용을 입력하세요.",
	    address_result : "주소록 검색결과",
	    employee_result : "임직원 검색결과",
	    to_address_count : "받는 사람",
	    cc_address_count : "참조",
	    bcc_address_count : "숨은 참조",
	    today : "오늘",
	    yesterday : "어제",
	    long_ago : "오래전",
	    week_mark : "요일",
	    week_sun : "일",
	    week_mon : "월",
	    week_tues : "화",
	    week_wednes : "수",
	    week_thurs : "목",
	    week_fri : "금",
	    week_satur : "토",
	    period_year : "년",
	    period_month : "개월",
	    person_unit : "명 ",
	    work_calendar : "캘린더",
	    work_task : "작업",
	    work_parent : "상위작업",
	    work_attendance_users : "참석자",
	    work_attendance_users_for_task : "담당자",
	    work_share_users : "공유자",
	    work_share_user_permission_4 : "제목만공유",
	    work_share_user_permission_5 : "전체공유",
	    work_period : "일정",
	    work_period_allday : "종일",
	    work_schedule_my : "내일정",
	    work_task_select : "작업선택",
	    work_resource_select : "회의실예약",
	    work_schedule_has_schedule : "일정있음",
	    work_schedule_has_task : "작업있음",
	    work_schedule_has_report : "보고서있음",
	    work_schedule_cc : "일정참고자",
	    work_schedule_share_calendar : "공유 칼렌더",
	    work_schedule_view : "일정보기",
	    work_schedule_write : "일정작성",
	    work_task_list : "작업목록",
	    work_task_view : "작업보기",
	    work_task_write : "작업작성",
	    work_task_write_message : "할일을 입력하여 주세요",
	    work_my_report : "내 보고서",
	    work_report_list : "보고서목록",
	    work_report_view : "보고서보기",
	    work_report_write : "보고서작성",
	    work_report_write_message : "새로운 보고서를 입력하여 주세요",
	    work_plan_list : "내 업무계획",
	    work_plan_view : "내 업무계획",
	    work_plan_write : "업무계획 작성",
	    work_plan_write_message : "새로운 계획을 입력하여 주세요",
	    work_template : "템플릿",
	    template_select : "템플릿 선택",
	    resource_menu_my : "나의 예약 현황",
	    resource_simple_reserv : "간편예약",
	    resource_menu_reserve : "예약하기",
	    resource_request_reserve : "예약신청",
	    resource_info : "회의실정보",
	    resource_select_area : "지역선택",
	    resource_reserve_time : "예약시간",
	    resource_reserve_date : "예약일자",
	    resource_state_0 : "종료",
	    resource_state_1 : "예약중",
	    resource_state_2 : "요청",
	    resource_state_3 : "회의중",
	    resource_owner_ : "예약자",
	    resource_reserve : "예약",
	    resource_cancel : "예약취소",
	    resource_begin : "회의 시작",
	    resource_end : "회의 종료",
	    resource_view : "예약내용",
	    resource_owner : "예약자",
	    resource_user : "참석자",
	    resource_meeting_start : "예약시작",
	    resource_meeting_end : "예약종료",
	    resource_mandatory_user : "필수참석인원",
	    resource_select_user : "선택참석인원",
	    resource_reservation_type : "회의성격",
	    resource_reservation_time : "예약시간",
	    resource_user_count : "참석인원수",
	    resource_attendance : "참석인원",
	    resource_phone : "회사연락처",
	    resource_mobile_phone : "비상연락처",
	    resource_comp : "참석업체명",
	    resource_purpose : "사용목적",
	    resource_title : "예약명",
	    resource_resource_name : "자원명",
	    resource_contents : "설명",
	    resource_schedule_0 : "참석인원 선택",
	    resource_schedule_1 : "일정에 추가하기",
	    resource_rtype_1 : "의사결정",
	    resource_rtype_2 : "정보공유",
	    resource_rtype_3 : "보고",
	    resource_rtype_4 : "기타",
	    resource_meeting_time : "회의시간",
	    hint_tel : "\'-\'없이 입력하세요.",
	    time_start_time : "출근시간",
	    time_end_time : "퇴근시간",
	    time_goout_start_time : "외출시작",
	    time_goout_end_time : "외출종료",
	    time_ot_time : "OT 누적 시간",
	    time_week : "주",
	    time_month : "월",
	    time_save : "저장되었습니다",
	    time_attendance_start : "출근",
	    time_attendance_end : "퇴근",
	    time_attendance_goout : "외출",
	    profile : "Profile",
	    user_name_ : "이름:",
	    user_number_ : "사번:",
	    comp_name_ : "회사:",
	    dept_name_ : "부서:",
	    comp_dept_name_ : "회사/부서 :",
	    level_name_ : "직위:",
	    position_name_ : "직책:",
	    level_position_name_ : "직위/직책:",
	    jikgun_name_ : "직군:",
	    location_phone_ : "유선전화:",
	    mobile_phone_ : "휴대전화:",
	    mobile_sms_ : "SMS:",
	    email_address_ : "eMail:",
	    work_address_ : "근무지:",
	    unknown : "내용없음",
	    search_type_draft : "기안자",
	    search_type_review : "결재/합의자",
	    search_type_control : "통제",
	    search_type_accept : "담당",
	    search_type_approval : "승인자",
	    approval_doc_key : "문서번호",
	    approval_security : "보안등급",
	    approval_period : "보존기간",
	    approval_doc_class_name : "문서분류",
	    approval_display_name : "기안자",
	    approval_create_date : "기안일",
	    approval_complete_date : "완료일",
	    approval_create : "기안",
	    approval_complete : "결재",
	    approval_complete_all : "전결",
	    approval_opinion_hint : "의견을 입력하여 주세요.",
	    approval_status : "결재현황",
	    approval_process_name : "처리자",
	    approval_process_activity : "방법",
	    approval_process_process : "상태",
	    approval_process_create_date : "결재일",
	    approval_process_complete_date : "개봉일",
	    approval_complete_btnApproval : "승인",
	    approval_complete_btnBudgetControl : "예산통제",
	    approval_complete_btnBudgetSupply : "추가예산",
	    approval_complete_btnAssess : "평가-정",
	    approval_complete_btnAgree : "합의",
	    approval_complete_btnAcceptDecide : "담당전결",
	    approval_complete_btnDiff : "불합의",
	    approval_complete_btnAgain : "재검토",
	    approval_complete_btnReject : "반려",
	    approval_complete_title_confirm : "결재확인",
	    approval_complete_message_confirm : "진행 하시겠습니까?",
	    approval_complete_message_empty_opnion : "의견을 입력 해주세요.",
	    approval_complete_message_success : "처리가 완료 되었습니다.",
	    approval_complete_message_unsupported : "비밀번호가 설정 된 결재문서는 모바일에서 지원하지 않습니다.",
	    home_notice : "Notice",
	    home_press : "한라路",
	    home_notice_00006 : "MBco News",
	    home_press_00006 : "BROSE News",
	    home_notice_00008 : "MHE News",
	    home_press_00008 : "HELLA News",
	    setting : "설정",
	    push_setting : "알림 설정",
	    language_setting : "언어 설정",
	    company_setting : "회사 설정",
	    main_setting : "메인화면 설정",
	    simple_password : "간편 비밀번호",
	    approval_push : "결재처리 알림",
	    approval_cc_push : "수신문서 알림",
	    work_schedule_push : "일정 알림",
	    work_task_push : "작업 알림",
	    work_report_push : "보고서 알림",
	    logout : "로그아웃",
	    lang_kor : "한글",
	    lang_eng : "영문",
	    lang_chn : "중문",
	    lang_jpn : "일문",
	    lang_etc : "기타",
	    navigation_drawer_open : "Open navigation drawer",
	    navigation_drawer_close : "Close navigation drawer",
	    hallam_home_title : "Hanmaru",
	    hallam_slogan : "HALLA One-body Communication Portal",
	    hallam_customer_center : "Custom Center  |   (02) 3434 – 5272 / 5274",
	    hallam_copyright : "Copyright© HALLA GROUP. All rights reserved",
	    hallam_reset_lock_password : "간편 비밀번호 설정",
	    hallam_require_user_id : "아이디를 입력하세요.",
	    hallam_require_password : "비밀번호를 입력하세요.",
	    mobilegw_home_title : "GroupWare",
	    mobilegw_customer_center : "GROUPWARE RENEWAL",
	    mobilegw_copyright : "만도헬라그룹웨어가 새롭게 태어납니다.",
	    mobilegw_reset_lock_password : "간편 로그인 비밀번호 설정 &gt;",
	    mobilegw_require_user_id : "ID 입력",
	    mobilegw_require_password : "PASSWORD 입력",
	    attendance : "근태관리",
	    goout_start : "시작",
	    goout_end : "종료",
	    hallaIn : "한라지식인",
	    midasHelp : "그룹실적보고",
	    noRead : "안읽음",
	    important : "중요",
	    flag : "플래그",
	    mailSync : "메일박스 동기화",
		approval_complete_all_date : "전결일",
		pull_to_refresh : "당겨서 놓으면 새로고침 됩니다",
		approval_box : "결재함",
		check_all : "전체체크",
		un_check_all : "전체해제",
		mail_remove : "메일 삭제",
		reply_all : "전체 회신",
		move_mail_box_select : "이동할 메일함 선택",
		setting_pin_password : "간편 비밀번호 6자리를 입력해 주세요",
		auto_login : "자동 로그인",
		setting_pin_password_text1 : "간편 비밀번호 설정을 위해",
		setting_pin_password_text2 : "한마루 ID와 PASSWORD를 입력해주세요",
		input_user_pin_number_text : "사용할 숫자 6자리 비밀번호를 입력해주세요 ",
		done : "완료",
		add_required : "필수추가",
		add_select : "선택추가",
		from : "부터",
		during : "동안",
		reset : "재설정",
		share_calendar : "공유캘린더",
		work_schedule_add : "일정추가",
		resource_select : "회의실 선택",
		notice : "공지사항",
		toast_setting_result : "설정변경이 적용 되었습니다.",
		setting_flagged : "플래그가 설정 되었습니다.",
		setting_un_flagged : "플래그가 해제 되었습니다.",
		setting_flag_fail : "플래그 설정/해제에 실패했습니다.",
		mail_move_success : "메일을 이동했습니다.",
		mail_move_fail : "메일이동 실패했습니다.",
		mail_remove_success : "메일을 삭제했습니다.",
		mail_remove_fail : "메일 삭제 실패했습니다.",
		send_mail_success : "메일 발송 완료",
		last_list : "마지막 리스트 입니다",
		data_load_fail : "데이터 불러오기 실패",
		toast_login_fail : "로그인에 실패하였습니다",
		toast_setting_pin_number_error : "핀번호는 연속된 숫자(111,123)를 사용할 수 없습니다.",
		toast_setting_pin_number_complete : "간편 비밀번호 설정이 완료되었습니다.",
		toast_setting_pin_number_fail : "간편 비밀번호 설정 실패",
		toast_setting_pin_number_warn : "간편 비밀번호를 설정해 주세요",
		toast_pin_number_over_period : "간편 비밀번호 변경 후 이용 가능합니다",
		toast_account_lock : "계정이 잠겼습니다. 한마루 사이트에서 잠금해제 후 사용 가능합니다",
		toast_device_lock : "해당 디바이스는 접속차단 상태입니다. 한마루 사이트에서 차단해제후 사용가능합니다.",
		taost_login_fail_msg1 : "로그인 실패 [시도횟수 ",
		am : "오전",
		pm : "오후",
		contents : "내용",
	},

	ENG: {
		message_more_back : "Press the back button again to exit.",
		message_dont_open_file : "Download completed. At the top, you can open the file in the status bar.",
		service_exception_expired_login_key : "The certificate has expired.",
		service_exception_invalid_login_key : " Authentication key is invalid.",
		service_exception_service : " There was a problem with the server.",
		service_exception_io : " There is a problem with the communication..",
		service_exception_etc : " An error has occurred.",
		warn_empty_message : " No data found.",
		warn_input_message : " Please enter a search term.",
		signin : "Sign in",
		login : "Login",
		simple_login : " Easy Login ",
		general_login : " General Login ",
		news : "Main",
		work : "Work Diary",
		mail : "Mail",
		approval : " Approval ",
		board : " Notice Board ",
		organ : " Organization chart ",
		resource : "Resource reservation",
		time : "Attendance Manage",
		gqms : "G-QMS",
		home_news : "Main",
		home_work : "Work Diary",
		home_mail : " E-mail ",
		home_approval : " Electronic approval ",
		home_board : " Notice Board ",
		home_organ : " Organization chart ",
		home_resource : "Resource reservation",
		unread : "Unread",
		flagged : " Flagged ",
		today_mails : "Today\'s mail",
		close : "Close",
		ok : " Confirm ",
		save : "Save",
		yes : "Yes",
		no : "No",
		add : "Add",
		apply : " Apply ",
		choice : "Select",
		write_mail : " Writing mail ",
		view_mail : " View Mail ",
		send : "Send",
		attach : " Attach ",
		reply : "Reply",
		forward : "Forward",
		move_message : " Mail move ",
		move_message_abbr : "Move",
		set_flag : " Show flag ",
		set_flag_abbr : " Display ",
		clear_flag : " Flag off ",
		set_read : " Mark as read ",
		set_unread : " Mark as unread ",
		bookmark : " Favorites ",
		search : "Search",
		find : "Find",
		edit : "Edit",
		remove : " Delete ",
		cancel : "Cancel",
		option : "Option",
		modify : "Modify",
		remove_message : " Are you sure you want to delete?",
		set_flag_message : " Flag registered.",
		clear_flag_message : "Flag canceled.",
		prev : " Previous ",
		next : "Next",
		from_address_ : " Sender:",
		to_address_ : " Recipient:",
		cc_address_ : "CC:",
		bcc_address_ : "BCC:",
		from_address : "Sender:",
		to_address : "Recipient",
		cc_address : " CC ",
		bcc_address : " BCC ",
		attach_files : "Attachment",
		to_detail : "Detail",
		view_detail : " View_detail ",
		view_summary : "View summary",
		mail_write : "Write mail",
		me_address : " Write to me ",
		all : "All",
		subject : "Title",
		body : " Body ",
		sender : "Sender",
		receive : "Recipirnt",
		subjectbody : "Title+Body",
		reg_user_name : "Writer",
		reg_date : "Written date",
		search_hint : " Please enter a search term.",
		subject_hint : "Please enter a subject term.",
		receive_hint : "Please enter a receive term.",
		selected_message : " Selected",
		more_view : "View more",
		content_hint : " Please enter content.",
		address_result : "Search results of address",
		employee_result : " Search results of employee",
		to_address_count : "Recipient",
		cc_address_count : "Carbon copy",
		bcc_address_count : "Blind carbon copy",
		today : "Today",
		yesterday : "Yesterday",
		long_ago : "Long ago",
		week_mark : "Day of the week",
		week_sun : "Day",
		week_mon : "Monday",
		week_tues : "Tuesday",
		week_wednes : "Wednesday",
		week_thurs : "Thursday",
		week_fri : "Friday",
		week_satur : "Saturday",
		period_year : "Year",
		period_month : "Month",
		person_unit : "person",
		work_calendar : "Calendar",
		work_task : "Work task",
		work_parent : "Parent task",
		work_attendance_users : "Attendants",
		work_attendance_users_for_task : "Manager",
		work_share_users : "Sharers",
		work_share_user_permission_4 : "Share title only",
		work_share_user_permission_5 : "Total shares",
		work_period : "Schedule",
		work_period_allday : "All Day",
		work_schedule_my : "My Schedule",
		work_task_select : "Select an action",
		work_resource_select : "Conference room reservation",
		work_schedule_has_schedule : "Have a schedule",
		work_schedule_has_task : "Have a task",
		work_schedule_has_report : "Have a report",
		work_schedule_cc : "Schedule CC",
		work_schedule_share_calendar : "Share Calendar",
		work_schedule_view : "View schedule",
		work_schedule_write : "Create schedule",
		work_task_list : "Task list",
		work_task_view : "View task",
		work_task_write : "Create task",
		work_task_write_message : "Please enter your to do",
		work_my_report : "My Report",
		work_report_list : "Report list",
		work_report_view : "View report",
		work_report_write : "Write report",
		work_report_write_message : " Please enter a new report ",
		work_plan_list : "List of plans",
		work_plan_view : "View Plan",
		work_plan_write : "Create a plan",
		work_plan_write_message : "Please enter a new plan.",
		work_template : "Template",
		template_select : "Select Templates",
		resource_menu_my : "My Reservation",
		resource_simple_reserv : "Simple Reservation",
		resource_menu_reserve : "To make a reservation",
		resource_request_reserve : "Reservation application",
		resource_info : "Meeting Room Information",
		resource_select_area : "Area Selection",
		resource_reserve_time : "Reservation time",
		resource_reserve_date : "Reservation date",
		resource_state_0 : "Termination",
		resource_state_1 : "Booking",
		resource_state_2 : "Request",
		resource_state_3 : "In a meeting",
		resource_owner_ : "Booker",
		resource_reserve : "Reservation",
		resource_cancel : "Resource Cancel",
		resource_begin : "Meeting start",
		resource_end : "End of meeting",
		resource_view : "Reservation details",
		resource_owner : "Booker",
		resource_user : "Attendee",
		resource_meeting_start : "Meeting start",
	    resource_meeting_end : "Reservation end",
		resource_mandatory_user : "Required attendance",
		resource_select_user : "Optional attendance",
		resource_reservation_type : "Meeting Type",
		resource_reservation_time : "Reservation time",
		resource_user_count : "Number of Attendees",
		resource_attendance : "Attendance",
		resource_phone : "Company Contacts",
		resource_mobile_phone : "Emergency contact",
		resource_comp : "Name of attending Company",
		resource_purpose : "Intended use",
		resource_title : "Reservation name",
		resource_resource_name : "Resource name",
		resource_contents : "Explanation",
		resource_schedule_0 : "Select participants",
		resource_schedule_1 : "Add to Calendar",
		resource_rtype_1 : "Decision making",
		resource_rtype_2 : "Information sharing",
		resource_rtype_3 : "Report",
		resource_rtype_4 : "Etc",
		resource_meeting_time : "Meeting time",
		hint_tel : "Please enter without \'-\'",
		time_start_time : "working time",
		time_end_time : "Time off",
		time_ot_time : "OT Accumulated time",
		time_week : "Week",
		time_month : "Month",
		time_save : "Saved",
		time_attendance_start : "Attendance",
	  time_attendance_end : "Leave work",
	  time_attendance_goout : "Going out",
		profile : "Profile",
		user_name_ : "Name:",
		user_number_ : "Business number:",
		comp_name_ : "Company:",
		dept_name_ : "Department:",
		comp_dept_name_ : "Company/Department:",
		level_name_ : "Position:",
		position_name_ : "Duty position:",
		level_position_name_ : "Position/Duty position:",
		jikgun_name_ : "Business group:",
		location_phone_ : "Telephone:",
		mobile_phone_ : "Mobile:",
		mobile_sms_ : "SMS:",
		email_address_ : "eMail:",
		work_address_ : "Business location:",
		unknown : "No contents",
		search_type_draft : "Drafter",
		search_type_review : "Approval/Agreement",
		search_type_control : "Control",
		search_type_accept : "Manager",
		search_type_approval : "Approver",
		approval_doc_key : "Document number",
		approval_security : "Security level",
		approval_period : " Retention period ",
		approval_doc_class_name : " Document classification ",
		approval_display_name : "Drafter",
		approval_create_date : "Drafting date",
		approval_complete_date : " Completion date ",
		approval_create : "Draft",
		approval_complete : "Approval",
		approval_complete_all : "Final approval",
		approval_opinion_hint : "Please enter your opinion.",
		approval_status : "Approval status",
		approval_process_name : "Processor",
		approval_process_activity : "Process method",
		approval_process_process : "Status",
		approval_process_create_date : "Approval date",
		approval_process_complete_date : "Release date",
		approval_complete_btnApproval : "Approval",
		approval_complete_btnBudgetControl : "Budget control",
		approval_complete_btnBudgetSupply : "Additional budget",
		approval_complete_btnAssess : "Evaluation - ",
		approval_complete_btnAgree : "Agreed by",
		approval_complete_btnAcceptDecide : "Draft decision",
		approval_complete_btnDiff : "Dissent",
		approval_complete_btnAgain : " Reexamination ",
		approval_complete_btnReject : "Rejected",
		approval_complete_title_confirm : "Approval confirm",
		approval_complete_message_confirm : " Do you want to proceed?",
		approval_complete_message_empty_opnion : " Please enter your opinion.",
		approval_complete_message_success : "Process complete.",
		approval_complete_message_unsupported : " Approval documents with passwords are not supported by mobile.",
		home_notice : "Notice",
		home_press : "Halla Way",
		home_notice_00006 : "MBco News",
		home_press_00006 : "BROSE News",
		home_notice_00008 : "MHE News",
		home_press_00008 : "HELLA News",
		setting : "Setting",
		push_setting : "Push Setting",
		language_setting : "Language setting",
		company_setting : "Company setting",
		main_setting : "Main page",
		simple_password : "Simple password",
		approval_push : "Approval push",
		approval_cc_push : "Receiving document push",
		work_schedule_push : "Schedule push",
		work_task_push : "Task push",
		work_report_push : "Report push",
		logout : "Logout",
		lang_kor : "Korean",
		lang_eng : "English",
		lang_chn : "Chinese",
		lang_jpn : "Japanese",
		lang_etc : "etc",
		navigation_drawer_open : "Open navigation drawer",
		navigation_drawer_close : "Close navigation drawer",
		hallam_home_title : "Hanmaru",
		hallam_slogan : "HALLA One-body Communication Portal",
		hallam_customer_center : "Custom Center | (02) 3434 – 5272 / 5274",
		hallam_copyright : "Copyright© HALLA GROUP. All rights reserved",
		hallam_reset_lock_password : " Easy password setting ",
		hallam_require_user_id : " Please enter your ID.",
		hallam_require_password : " Please enter a password.",
		mobilegw_home_title : "GroupWare",
		mobilegw_customer_center : "GROUPWARE RENEWAL",
		mobilegw_copyright : "Mando Hella Groupware is being born anew.",
		mobilegw_reset_lock_password : "Simple Login Password Settings &gt;",
		mobilegw_require_user_id : "Enter ID",
		mobilegw_require_password : "Enter PASSWORD",
		attendance : "Attendance",
		hallaIn : "HallaIn",
		midasHelp : "MidasHelp",
		noRead : "UnRead",
		important : "Important",
		flag : "Flag",
		attach : "Attach",
		mailSync : "MailBox Sync",
		approval_complete_all_date : "Complete All Date",
		pull_to_refresh : "Pull To Refresh",
		approval_box : "Approval Box",
		check_all : "Check All",
		un_check_all : "UnCheck All",
		mail_remove : "Remove Mail",
		reply : "Reply",
		reply_all : "Reply All",
		move_mail_box_select : "Select MailBox",
		setting_pin_password : "Please enter a 6-digit PIN code",
		auto_login : "Auto Login",
		setting_pin_password_text1 : "To set a simple password",
		setting_pin_password_text2 : "Please enter a HANMARU ID and a PASSWORD",
		input_user_pin_number_text : "Please enter a 6-digit password to use",
		done : "Done",
		add_required : "Required Add",
		add_select : "Select Add",
		from : "From",
		during : "During",
		reset : "Reset",
		share_calendar : "Share Calendar",
		work_schedule_add : "Add Schedule",
		resource_select : "Select a conference room",
		notice : "Notice",
		toast_setting_result : "Settings change has been applied",
		setting_flagged : "Flag set",
		setting_un_flagged : "Flag has been disabled.",
		setting_flag_fail : "Flag on/off failed",
		//중문 아래부터 적용할것.
		mail_move_success : "Mail moved successfully",
		mail_move_fail : "Mail movement failed.",
		mail_remove_success : "Deleted mail",
		mail_remove_fail : "Failed to delete mail",
		send_mail_success : "Completed sending of mail",
		last_list : "Last list.",
		data_load_fail : "Failed to retrieve data",
		toast_login_fail : "Login failed",
		toast_setting_pin_number_error : "Pin numbers cannot be a continuous number (111,123)",
		toast_setting_pin_number_complete : "Pin numbers setup is complete.",
		toast_setting_pin_number_fail : "Pin numbers setting failed.",
		toast_setting_pin_number_warn : "Please set the pin number.",
		toast_pin_number_over_period : "You can use it after changing your password.",
		toast_account_lock : "Your account is locked. Available after unlocking from HANMARU PC Website",
		toast_device_lock : "The device is locked. Available after unlocking from HANMARU PC Website",
		taost_login_fail_msg1 : "Login failed. [Try ",
		am : "AM",
		pm : "PM",
		contents : "Body",
	},
	CHN : {
		message_more_back : "点下一步结束.",
	    message_dont_open_file : "다운로드가 완료되었습니다. 상단에 상태표시줄에서 파일을 열수 있습니다.",
	    service_exception_expired_login_key : "认证已到期.",
	    service_exception_invalid_login_key : "认证无效.",
	    service_exception_service : "服务器发生问题.",
	    service_exception_io : "通讯异常.",
	    service_exception_etc : "发生错误.",
	    warn_empty_message : "无搜索数据.",
	    warn_input_message : "请输入搜索内容.",
	    signin : "Sign in",
	    login : "登录",
	    simple_login : "快速登录",
	    general_login : "一般登录",
	    news : "首页",
	    work : "工作日志",
	    mail : "邮件",
	    approval : "审批",
	    board : "公告板",
	    organ : "组织图",
	    resource : "자원예약",
	    time : "근태관리",
	    gqms : "G-QMS",
	    home_news : "首页",
	    home_work : "工作日志",
	    home_mail : "电子邮件",
	    home_approval : "电子审批",
	    home_board : "公告板",
	    home_organ : "组织图",
	    home_resource : "자원예약",
	    unread : "未读",
	    flagged : "已标记",
	    today_mails : "今日邮件",
	    close : "닫기",
	    ok : "确认",
	    save : "저장",
	    yes : "是",
	    no : "否",
	    add : "추가",
	    apply : "适用",
	    choice : "선택",
	    write_mail : "写信",
	    view_mail : "查看邮件",
	    send : "发送",
	    attach : "附件",
	    reply : "回复",
	    forward : "传递",
	    move_message : "邮件移动",
	    move_message_abbr : "移动",
	    set_flag : "旗帜标记",
	    set_flag_abbr : "标记",
	    clear_flag : "旗帜解除",
	    set_read : "已读标记",
	    set_unread : "未读标记",
	    bookmark : "收藏夹",
	    search : "搜索",
	    find : "조회",
	    edit : "编辑",
	    remove : "删除",
	    cancel : "取消",
	    option : "옵션",
	    modify : "修改",
	    remove_message : "是否删除?",
	    set_flag_message : "已标记旗帜.",
	    clear_flag_message : "已解除旗帜.",
	    prev : "上一步",
	    next : "下一步",
	    from_address_ : "发件人:",
	    to_address_ : "收件人:",
	    cc_address_ : "抄送:",
	    bcc_address_ : "密抄:",
	    from_address : "发件人:",
	    to_address : "收件人",
	    cc_address : "抄送",
	    bcc_address : "密抄",
	    attach_files : "附件",
	    to_detail : "자세히",
	    view_detail : "查看明细",
	    view_summary : "简单查看",
	    mail_write : "写信",
	    me_address : "对我",
	    all : "全体",
	    subject : "标题",
	    body : "正文",
	    sender : "发件人",
	    receive : "收件人",
	    subjectbody : "标题+正文",
	    reg_user_name : "制作者",
	    reg_date : "制作日",
	    search_hint : "请输入搜索内容.",
	    subject_hint : "请输入搜索内容.",
	    receive_hint : "请输入搜索内容.",
	    selected_message : "已选择",
	    more_view : "查看更多",
	    content_hint : "请输入内容.",
	    address_result : "通信录搜索结果",
	    employee_result : "员工搜索结果",
	    to_address_count : "收件人",
	    cc_address_count : "抄送",
	    bcc_address_count : "密抄",
	    today : "今日",
	    yesterday : "昨天",
	    long_ago : "更早",
	    week_mark : "星期",
	    week_sun : "星期日",
	    week_mon : "星期一",
	    week_tues : "星期二",
	    week_wednes : "星期三",
	    week_thurs : "星期四",
	    week_fri : "星期五",
	    week_satur : "星期六",
	    period_year : "年",
	    period_month : "个月",
	    person_unit : "명 ",
	    work_calendar : "日历",
	    work_task : "工作",
	    work_parent : "上级工作",
	    work_attendance_users : "参加者",
	    work_attendance_users_for_task : "담당자",
	    work_share_users : "共享者",
	    work_share_user_permission_4 : "제목만공유",
	    work_share_user_permission_5 : "전체공유",
	    work_period : "日程",
	    work_period_allday : "종일",
	    work_schedule_my : "내일정",
	    work_task_select : "작업선택",
	    work_resource_select : "회의실예약",
	    work_schedule_has_schedule : "日程已存在",
	    work_schedule_has_task : "工作已存在",
	    work_schedule_has_report : "报告书已存在",
	    work_schedule_cc : "日程参考者",
	    work_schedule_share_calendar : "공유 칼렌더",
	    work_schedule_view : "查看日程",
	    work_schedule_write : "制定日程",
	    work_task_list : "工作目录",
	    work_task_view : "查看工作",
	    work_task_write : "制定工作",
	    work_task_write_message : "请输入工作内容",
	    work_my_report : "我的报告",
	    work_report_list : "报告书目录",
	    work_report_view : "查看报告书",
	    work_report_write : "制作报告书",
	    work_report_write_message : "请输入新报告书",
	    work_plan_list : "계획목록",
	    work_plan_view : "계획보기",
	    work_plan_write : "계획작성",
	    work_plan_write_message : "새로운 계획을 입력하여 주세요",
	    work_template : "템플릿",
	    template_select : "템플릿 선택",
	    resource_menu_my : "나의 예약 현황",
	    resource_simple_reserv : "간편예약",
	    resource_menu_reserve : "예약하기",
	    resource_request_reserve : "예약신청",
	    resource_info : "회의실정보",
	    resource_select_area : "지역선택",
	    resource_reserve_time : "예약시간",
	    resource_reserve_date : "예약일자",
	    resource_state_0 : "종료",
	    resource_state_1 : "예약중",
	    resource_state_2 : "요청",
	    resource_state_3 : "회의중",
	    resource_owner_ : "예약자",
	    resource_reserve : "예약",
	    resource_cancel : "예약 취소",
	    resource_begin : "회의 시작",
	    resource_end : "회의 종료",
	    resource_view : "예약내용",
	    resource_owner : "예약자",
	    resource_user : "참석자",
	    resource_meeting_start : "예약시작",
	    resource_meeting_end : "예약종료",
	    resource_mandatory_user : "필수참석인원",
	    resource_select_user : "선택참석인원",
	    resource_reservation_type : "회의성격",
	    resource_reservation_time : "예약시간",
	    resource_user_count : "참석인원수",
	    resource_attendance : "참석인원",
	    resource_phone : "회사연락처",
	    resource_mobile_phone : "비상연락처",
	    resource_comp : "참석업체명",
	    resource_purpose : "사용목적",
	    resource_title : "예약명",
	    resource_resource_name : "자원명",
	    resource_contents : "설명",
	    resource_schedule_0 : "참석인원 선택",
	    resource_schedule_1 : "일정에 추가하기",
	    resource_rtype_1 : "의사결정",
	    resource_rtype_2 : "정보공유",
	    resource_rtype_3 : "보고",
	    resource_rtype_4 : "기타",
	    resource_meeting_time : "회의시간",
	    hint_tel : "\'-\'없이 입력하세요.",
	    time_start_time : "출근시간",
	    time_end_time : "퇴근시간",
	    time_ot_time : "OT 누적 시간",
	    time_week : "주",
	    time_month : "월",
	    time_save : "저장되었습니다",
	    time_attendance_start : "출근",
	    time_attendance_end : "퇴근",
	    time_attendance_goout : "외출",
	    profile : "Profile",
	    user_name_ : "姓名:",
	    user_number_ : "工号:",
	    comp_name_ : "公司:",
	    dept_name_ : "部门:",
	    comp_dept_name_ : "公司/部门:",
	    level_name_ : "职位:",
	    position_name_ : "职责:",
	    level_position_name_ : "职位/职责:",
	    jikgun_name_ : "职业:",
	    location_phone_ : "座机:",
	    mobile_phone_ : "手机:",
	    mobile_sms_ : "SMS:",
	    email_address_ : "eMail:",
	    work_address_ : "工作地点:",
	    unknown : "无内容",
	    search_type_draft : "起案者",
	    search_type_review : "审批/协议者",
	    search_type_control : "控制",
	    search_type_accept : "担当",
	    search_type_approval : "审批者",
	    approval_doc_key : "文件编号",
	    approval_security : "安全等级",
	    approval_period : "保存期限",
	    approval_doc_class_name : "文件分类",
	    approval_display_name : "起案者",
	    approval_create_date : "起案日",
	    approval_complete_date : "完成日",
	    approval_create : "起案",
	    approval_complete : "审批",
	    approval_complete_all : "决裁",
	    approval_opinion_hint : "请输入意见.",
	    approval_status : "审批现况",
	    approval_process_name : "处理者",
	    approval_process_activity : "方法",
	    approval_process_process : "状态",
	    approval_process_create_date : "审批日",
	    approval_process_complete_date : "阅览日",
	    approval_complete_btnApproval : "承认",
	    approval_complete_btnBudgetControl : "预算控制",
	    approval_complete_btnBudgetSupply : "追加预算",
	    approval_complete_btnAssess : "评价-정",
	    approval_complete_btnAgree : "协议",
	    approval_complete_btnAcceptDecide : "担当决裁",
	    approval_complete_btnDiff : "不协议",
	    approval_complete_btnAgain : "重新审查",
	    approval_complete_btnReject : "驳回",
	    approval_complete_title_confirm : "审批确认",
	    approval_complete_message_confirm : "是否继续?",
	    approval_complete_message_empty_opnion : "请输入意见.",
	    approval_complete_message_success : "已处理完成.",
	    approval_complete_message_unsupported : "移动客户端不支持加密的审批文件.",
	    home_notice : "Notice",
	    home_press : "汉拿路",
	    home_notice_00006 : "MBco News",
	    home_press_00006 : "BROSE News",
	    home_notice_00008 : "MHE News",
	    home_press_00008 : "HELLA News",
	    setting : "设置",
	    push_setting : "通知设置",
	    language_setting : "语言设置",
	    company_setting : "公司设置",
	    main_setting : "首页",
	    simple_password : "快速密码",
	    approval_push : "审批提醒",
	    approval_cc_push : "收件箱提示",
	    work_schedule_push : "日程提醒",
	    work_task_push : "工作提醒",
	    work_report_push : "报告书提醒",
	    logout : "注销",
	    lang_kor : "韩文",
	    lang_eng : "英文",
	    lang_chn : "中文",
	    lang_jpn : "日文",
	    lang_etc : "其它",
	    navigation_drawer_open : "Open navigation drawer",
	    navigation_drawer_close : "Close navigation drawer",
	    hallam_home_title : "Hanmaru",
	    hallam_slogan : "HALLA One-body Communication Portal",
	    hallam_customer_center : "Custom Center  |   (02) 3434 – 5272 / 5274",
	    hallam_copyright : "Copyright© HALLA GROUP. All rights reserved",
	    hallam_reset_lock_password : "快速设置密码",
	    hallam_require_user_id : "请输入用户名.",
	    hallam_require_password : "请输入密码.",
	    mobilegw_home_title : "GroupWare",
	    mobilegw_customer_center : "GROUPWARE RENEWAL",
	    mobilegw_copyright : "만도헬라그룹웨어가 새롭게 태어납니다.",
	    mobilegw_reset_lock_password : "간편 로그인 비밀번호 설정 &gt;",
	    mobilegw_require_user_id : "ID 입력",
	    mobilegw_require_password : "PASSWORD 입력",
	    attendance : "考勤管理",
			//아래로 중어번역 필요
	    hallaIn : "HallaIn",
	    midasHelp : "MidasHelp",
	    noRead : "UnRead",
	    important : "Important",
	    flag : "Flag",
	    attach : "Attach",
	    mailSync : "MailBox Sync",
			approval_complete_all_date : "Complete All Date",
			pull_to_refresh : "Pull To Refresh",
			approval_box : "Approval Box",
			check_all : "Check All",
			un_check_all : "UnCheck All",
			mail_remove : "Remove Mail",
			reply : "Reply",
			reply_all : "Reply All",
			move_mail_box_select : "Select MailBox",
			setting_pin_password : "请输入6位数的PIN码",
			auto_login : "自动登录",
			setting_pin_password_text1 : "为了设置简便密码",
			setting_pin_password_text2 : "请输入Hanmaru ID和 PASWORD。",
			input_user_pin_number_text : "请输入使用数字6位数密码。",
			done : "完成",
			add_required : "必须追加",
			add_select : "选择追加",
			during : "在……期间",
			reset : "重新设定",
			share_calendar : "共享日历",
			work_schedule_add : "日程追加",
			resource_select : "选择会议室",
			notice : "公告事项",
			toast_setting_result : "适用设定变更。",
			setting_flagged : "已设定旗舰。",
			setting_un_flagged : "旗舰产品已解除。",
			setting_flag_fail : "设置/解除旗舰",
	},
	JPN : {

	},
	ETC : {

	}
}
