/*
 GNU Lesser General Public License, http://www.gnu.org/copyleft/lesser.html
 @author  Jan Odvarko, http://odvarko.cz
 @created 2008-06-15
 @updated 2013-04-08
 @link    http://jscolor.com
*/
Array.prototype.indexOf||(Array.prototype.indexOf=function(d,f){f=f||0;for(var a=this.length;f<a;){if(this[f]===d)return f;++f}return-1});
var jscolor={dir:"../images/editor/jscolor/",bindClass:"color",binding:!0,preloading:!0,clickedElem:null,styleColor:"",actionType:"",excuteFn:null,install:function(){jscolor.addEvent(window,"load",jscolor.init)},init:function(){jscolor.binding&&jscolor.bind();jscolor.preloading&&jscolor.preload()},getDir:function(){if(!jscolor.dir){var d=jscolor.detectDir();jscolor.dir=!1!==d?d:"jscolor/"}return jscolor.dir},detectDir:function(){for(var d=location.href,f=document.getElementsByTagName("base"),a=0;a<
f.length;a+=1)f[a].href&&(d=f[a].href);f=document.getElementsByTagName("script");for(a=0;a<f.length;a+=1)if(f[a].src&&/(^|\/)jscolor\.js([?#].*)?$/i.test(f[a].src))return d=(new jscolor.URI(f[a].src)).toAbsolute(d),d.path=d.path.replace(/[^\/]+$/,""),d.query=null,d.fragment=null,d.toString();return!1},bind:function(){for(var d=new RegExp("(^|\\s)("+jscolor.bindClass+")\\s*(\\{[^}]*\\})?","i"),f=document.getElementsByTagName("div"),a=0;a<f.length;a+=1){var n;if(!f[a].color&&f[a].className&&(n=f[a].className.match(d))){var x=
{};if(n[3])try{x=(new Function("return ("+n[3]+")"))()}catch(G){}f[a].color=new jscolor.color(f[a],x)}}},preload:function(){for(var d in jscolor.imgRequire)jscolor.imgRequire.hasOwnProperty(d)&&jscolor.loadImage(d)},images:{pad:[130,81],sld:[15,81],cross:[20,20],arrow:[3,0]},imgRequire:{},imgLoaded:{},requireImage:function(d){jscolor.imgRequire[d]=!0},loadImage:function(d){jscolor.imgLoaded[d]||(jscolor.imgLoaded[d]=new Image,jscolor.imgLoaded[d].src=jscolor.getDir()+d)},fetchElement:function(d){return"string"===
typeof d?document.getElementById(d):d},addEvent:function(d,f,a){d.addEventListener?d.addEventListener(f,a,!1):d.attachEvent&&d.attachEvent("on"+f,a)},fireEvent:function(d,f){if(d)if(document.createEvent){var a=document.createEvent("HTMLEvents");a.initEvent(f,!0,!0);d.dispatchEvent(a)}else if(document.createEventObject)document.createEventObject();else if(d["on"+f])d["on"+f]()},getElementPos:function(d){var f=d,a=0,n=0;if(f.offsetParent){do a+=f.offsetLeft,n+=f.offsetTop;while(f=f.offsetParent)}for(;(d=
d.parentNode)&&"BODY"!==d.nodeName.toUpperCase();)a-=d.scrollLeft,n-=d.scrollTop;return[a,n]},getElementSize:function(d){return[d.offsetWidth,d.offsetHeight]},getRelMousePos:function(d){var f=0,a=0;d||(d=window.event);"number"===typeof d.offsetX?(f=d.offsetX,a=d.offsetY):"number"===typeof d.layerX&&(f=d.layerX,a=d.layerY);return{x:f,y:a}},getViewPos:function(){return"number"===typeof window.pageYOffset?[window.pageXOffset,window.pageYOffset]:document.body&&(document.body.scrollLeft||document.body.scrollTop)?
[document.body.scrollLeft,document.body.scrollTop]:document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[0,0]},getViewSize:function(){return"number"===typeof window.innerWidth?[window.innerWidth,window.innerHeight]:document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?[document.documentElement.clientWidth,document.documentElement.clientHeight]:
document.body&&(document.body.clientWidth||document.body.clientHeight)?[document.body.clientWidth,document.body.clientHeight]:[0,0]},URI:function(d){function f(a){for(var d="";a;)if("../"===a.substr(0,3)||"./"===a.substr(0,2))a=a.replace(/^\.+/,"").substr(1);else if("/./"===a.substr(0,3)||"/."===a)a="/"+a.substr(3);else if("/../"===a.substr(0,4)||"/.."===a)a="/"+a.substr(4),d=d.replace(/\/?[^\/]*$/,"");else if("."===a||".."===a)a="";else{var f=a.match(/^\/?[^\/]*/)[0];a=a.substr(f.length);d+=f}return d}
this.authority=this.scheme=null;this.path="";this.fragment=this.query=null;this.parse=function(a){a=a.match(/^(([A-Za-z][0-9A-Za-z+.-]*)(:))?((\/\/)([^\/?#]*))?([^?#]*)((\?)([^#]*))?((#)(.*))?/);this.scheme=a[3]?a[2]:null;this.authority=a[5]?a[6]:null;this.path=a[7];this.query=a[9]?a[10]:null;this.fragment=a[12]?a[13]:null;return this};this.toString=function(){var a="";null!==this.scheme&&(a=a+this.scheme+":");null!==this.authority&&(a=a+"//"+this.authority);null!==this.path&&(a+=this.path);null!==
this.query&&(a=a+"?"+this.query);null!==this.fragment&&(a=a+"#"+this.fragment);return a};this.toAbsolute=function(a){a=new jscolor.URI(a);var d=new jscolor.URI;if(null===a.scheme)return!1;null!==this.scheme&&this.scheme.toLowerCase()===a.scheme.toLowerCase()&&(this.scheme=null);null!==this.scheme?(d.scheme=this.scheme,d.authority=this.authority,d.path=f(this.path),d.query=this.query):(null!==this.authority?(d.authority=this.authority,d.path=f(this.path),d.query=this.query):(""===this.path?(d.path=
a.path,d.query=null!==this.query?this.query:a.query):("/"===this.path.substr(0,1)?d.path=f(this.path):(d.path=null!==a.authority&&""===a.path?"/"+this.path:a.path.replace(/[^\/]+$/,"")+this.path,d.path=f(d.path)),d.query=this.query),d.authority=a.authority),d.scheme=a.scheme);d.fragment=this.fragment;return d};d&&this.parse(d)},color:function(d,f,a,n,x,G){function z(b,a,d){if(null===b)return[d,d,d];var e=Math.floor(b),f=d*(1-a);b=d*(1-a*(e%2?b-e:1-(b-e)));switch(e){case 6:case 0:return[d,b,f];case 1:return[b,
d,f];case 2:return[f,d,b];case 3:return[f,b,d];case 4:return[b,f,d];case 5:return[d,f,b]}}function K(b,d){if(!jscolor.picker){jscolor.picker={box:document.createElement("div"),boxB:document.createElement("div"),pad:document.createElement("div"),padB:document.createElement("div"),padM:document.createElement("div"),sld:document.createElement("div"),sldB:document.createElement("div"),sldM:document.createElement("div"),btn:document.createElement("div"),boxC:document.createElement("div"),boxHEX:document.createElement("span"),
boxRGB:document.createElement("span"),btnS:document.createElement("span"),btnT:document.createTextNode(e.pickerCloseText),select:document.createElement("select"),option1:document.createElement("option"),option2:document.createElement("option"),btnOk:document.createElement("input"),btnCancle:document.createElement("input"),label:document.createElement("label"),labelR:document.createElement("label"),labelG:document.createElement("label"),labelB:document.createElement("label"),lbColor:document.createElement("input"),
lbColor2:document.createElement("input"),lbColorR:document.createElement("input"),lbColorG:document.createElement("input"),lbColorB:document.createElement("input"),inbottom:document.createElement("div"),bottom:document.createElement("div")};for(var a=0;a<jscolor.images.sld[1];a+=4){var f=document.createElement("div");f.style.height="4px";f.style.fontSize="1px";f.style.lineHeight="0";jscolor.picker.sld.appendChild(f)}jscolor.picker.sldB.appendChild(jscolor.picker.sld);jscolor.picker.box.appendChild(jscolor.picker.sldB);
jscolor.picker.box.appendChild(jscolor.picker.sldM);jscolor.picker.padB.appendChild(jscolor.picker.pad);jscolor.picker.box.appendChild(jscolor.picker.padB);jscolor.picker.box.appendChild(jscolor.picker.padM);jscolor.picker.btnS.appendChild(jscolor.picker.btnT);jscolor.picker.btn.appendChild(jscolor.picker.btnS);jscolor.picker.box.appendChild(jscolor.picker.btn);jscolor.picker.boxB.appendChild(jscolor.picker.box);jscolor.picker.boxC.style.margin="0 0 5px 0";jscolor.picker.boxC.style.padding="0";jscolor.picker.boxC.style.textAlign=
"left";jscolor.picker.boxC.style.marginBottom="5px";jscolor.picker.lbColor2.setAttribute("type","text");jscolor.picker.lbColor2.setAttribute("id","cp_lb_color2");jscolor.picker.lbColor2.setAttribute("disabled","disabled");jscolor.picker.lbColor2.style.border="solid 1px #c5c5c5";jscolor.picker.lbColor2.style.width="33px";jscolor.picker.lbColor2.style.backgroundColor="#ffffff";a=19;parent.DEXTTOP.DEXT5.browser.ie&&9>=parent.DEXTTOP.DEXT5.browser.ieVersion&&!parent.DEXTTOP.DEXT5.browser.quirks&&(a=15);
jscolor.picker.lbColor2.style.height=a+"px";jscolor.picker.lbColor2.style.marginLeft="-1px";jscolor.picker.boxHEX.style.display="inline-block";jscolor.picker.boxHEX.style.margin="0";jscolor.picker.boxHEX.style.padding="0";jscolor.picker.label.innerText="#";jscolor.picker.label.style.marginLeft="1px";jscolor.picker.label.style.color="#5d5d5d";jscolor.picker.label.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.label.style.fontSize="13px";jscolor.picker.lbColor.setAttribute("type",
"text");jscolor.picker.lbColor.setAttribute("id","cp_lb_color");jscolor.picker.lbColor.style.border="solid 1px #c5c5c5";jscolor.picker.lbColor.style.color="#5d5d5d";jscolor.picker.lbColor.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.lbColor.style.fontSize="13px";jscolor.picker.lbColor.style.width=parent.DEXTTOP.DEXT5.browser.ie&&9>=parent.DEXTTOP.DEXT5.browser.ieVersion&&!parent.DEXTTOP.DEXT5.browser.quirks?"98px":parent.DEXTTOP.DEXT5.browser.chrome?"108px":"107px";jscolor.picker.lbColor.style.height=
a+"px";jscolor.picker.lbColor.style.imeMode="disabled";jscolor.picker.lbColor.maxLength="6";parent.DEXTTOP.DEXT5.util.addEvent(jscolor.picker.lbColor,"keyup",function(c){try{jscolor.picker.lbColor2.style.backgroundColor="#"+jscolor.picker.lbColor.value}catch(b){jscolor.picker.lbColor2.style.backgroundColor="#ffffff"}});jscolor.picker.boxHEX.appendChild(jscolor.picker.label);jscolor.picker.boxHEX.appendChild(jscolor.picker.lbColor);var f="30px",l="3px";parent.DEXTTOP.DEXT5.browser.ie&&9>=parent.DEXTTOP.DEXT5.browser.ieVersion&&
!parent.DEXTTOP.DEXT5.browser.quirks?(f="25.5px",l=""):parent.DEXTTOP.DEXT5.browser.chrome&&(f="29.5px");jscolor.picker.labelR.innerText="R";jscolor.picker.labelR.style.color="#5d5d5d";jscolor.picker.labelR.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.labelR.style.fontSize="13px";jscolor.picker.labelR.style.marginLeft=l;jscolor.picker.lbColorR.setAttribute("type","text");jscolor.picker.lbColorR.setAttribute("id","cp_lb_color_r");jscolor.picker.lbColorR.style.border="solid 1px #c5c5c5";
jscolor.picker.lbColorR.style.width=f;jscolor.picker.lbColorR.style.height=a+"px";jscolor.picker.lbColorR.style.color="#5d5d5d";jscolor.picker.lbColorR.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.lbColorR.style.fontSize="13px";jscolor.picker.lbColorR.style.imeMode="disabled";jscolor.picker.lbColorR.maxLength="3";parent.DEXTTOP.DEXT5.util.addEvent(jscolor.picker.lbColorR,"keypress",function(c){var b=c.keyCode?c.keyCode:c.which;(48>b||57<b)&&parent.DEXTTOP.DEXT5.util.cancelEvent(c)});
parent.DEXTTOP.DEXT5.util.addEvent(jscolor.picker.lbColorR,"keyup",function(c){17==(c.keyCode?c.keyCode:c.which)&&(ctrlDown=!1);0>jscolor.picker.lbColorR.value?jscolor.picker.lbColorR.value=0:255<jscolor.picker.lbColorR.value?jscolor.picker.lbColorR.value=255:"0"!=jscolor.picker.lbColorR.value&&0==jscolor.picker.lbColorR.value.indexOf("0")&&(jscolor.picker.lbColorR.value=jscolor.picker.lbColorR.value.replace("0",""));try{jscolor.picker.lbColor2.style.backgroundColor="rgb("+jscolor.picker.lbColorR.value+
", "+jscolor.picker.lbColorG.value+", "+jscolor.picker.lbColorB.value+")"}catch(b){jscolor.picker.lbColor2.style.backgroundColor="rgb(255,255,255)"}});jscolor.picker.labelG.innerText="G";jscolor.picker.labelG.style.color="#5d5d5d";jscolor.picker.labelG.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.labelG.style.fontSize="13px";jscolor.picker.lbColorG.setAttribute("type","text");jscolor.picker.lbColorG.setAttribute("id","cp_lb_color_g");jscolor.picker.lbColorG.style.border=
"solid 1px #c5c5c5";jscolor.picker.lbColorG.style.width=f;jscolor.picker.lbColorG.style.height=a+"px";jscolor.picker.lbColorG.style.color="#5d5d5d";jscolor.picker.lbColorG.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.lbColorG.style.fontSize="13px";jscolor.picker.lbColorG.style.imeMode="disabled";jscolor.picker.lbColorG.maxLength="3";parent.DEXTTOP.DEXT5.util.addEvent(jscolor.picker.lbColorG,"keypress",function(c){var b=c.keyCode?c.keyCode:c.which;(48>b||57<b)&&parent.DEXTTOP.DEXT5.util.cancelEvent(c)});
parent.DEXTTOP.DEXT5.util.addEvent(jscolor.picker.lbColorG,"keyup",function(c){0>jscolor.picker.lbColorG.value?jscolor.picker.lbColorG.value=0:255<jscolor.picker.lbColorG.value?jscolor.picker.lbColorG.value=255:"0"!=jscolor.picker.lbColorG.value&&0==jscolor.picker.lbColorG.value.indexOf("0")&&(jscolor.picker.lbColorG.value=jscolor.picker.lbColorG.value.replace("0",""));try{jscolor.picker.lbColor2.style.backgroundColor="rgb("+jscolor.picker.lbColorR.value+", "+jscolor.picker.lbColorG.value+", "+jscolor.picker.lbColorB.value+
")"}catch(b){jscolor.picker.lbColor2.style.backgroundColor="rgb(255,255,255)"}});jscolor.picker.labelB.innerText="B";jscolor.picker.labelB.style.color="#5d5d5d";jscolor.picker.labelB.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.labelB.style.fontSize="13px";jscolor.picker.lbColorB.setAttribute("type","text");jscolor.picker.lbColorB.setAttribute("id","cp_lb_color_b");jscolor.picker.lbColorB.style.border="solid 1px #c5c5c5";jscolor.picker.lbColorB.style.width=f;jscolor.picker.lbColorB.style.height=
a+"px";jscolor.picker.lbColorB.style.color="#5d5d5d";jscolor.picker.lbColorB.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.lbColorB.style.fontSize="13px";jscolor.picker.lbColorB.style.imeMode="disabled";jscolor.picker.lbColorB.maxLength="3";parent.DEXTTOP.DEXT5.util.addEvent(jscolor.picker.lbColorB,"keypress",function(c){var b=c.keyCode?c.keyCode:c.which;(48>b||57<b)&&parent.DEXTTOP.DEXT5.util.cancelEvent(c)});parent.DEXTTOP.DEXT5.util.addEvent(jscolor.picker.lbColorB,
"keyup",function(c){17==(c.keyCode?c.keyCode:c.which)&&(ctrlDown=!1);0>jscolor.picker.lbColorB.value?jscolor.picker.lbColorB.value=0:255<jscolor.picker.lbColorB.value?jscolor.picker.lbColorB.value=255:"0"!=jscolor.picker.lbColorB.value&&0==jscolor.picker.lbColorB.value.indexOf("0")&&(jscolor.picker.lbColorB.value=jscolor.picker.lbColorB.value.replace("0",""));try{jscolor.picker.lbColor2.style.backgroundColor="rgb("+jscolor.picker.lbColorR.value+", "+jscolor.picker.lbColorG.value+", "+jscolor.picker.lbColorB.value+
")"}catch(b){jscolor.picker.lbColor2.style.backgroundColor="rgb(255,255,255)"}});jscolor.picker.boxRGB.style.margin="0";jscolor.picker.boxRGB.style.padding="0";jscolor.picker.boxRGB.appendChild(jscolor.picker.labelR);jscolor.picker.boxRGB.appendChild(jscolor.picker.lbColorR);jscolor.picker.boxRGB.appendChild(jscolor.picker.labelG);jscolor.picker.boxRGB.appendChild(jscolor.picker.lbColorG);jscolor.picker.boxRGB.appendChild(jscolor.picker.labelB);jscolor.picker.boxRGB.appendChild(jscolor.picker.lbColorB);
jscolor.picker.select.name="colorValue";jscolor.picker.select.id="colorValue";jscolor.picker.select.style.border="1px solid #c5c5c5";jscolor.picker.select.style.color="#5d5d5d";jscolor.picker.select.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.select.style.fontSize="13px";jscolor.picker.option1.value="hex";jscolor.picker.option1.innerText="HEX";jscolor.picker.option2.value="rgb";jscolor.picker.option2.innerText="RGB";jscolor.picker.select.appendChild(jscolor.picker.option1);
jscolor.picker.select.appendChild(jscolor.picker.option2);jscolor.picker.btnOk.setAttribute("type","button");jscolor.picker.btnOk.setAttribute("id","cp_btn_ok");jscolor.picker.btnOk.setAttribute("value",parent.DEXTTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.ok);jscolor.picker.btnOk.style.width="42px";jscolor.picker.btnOk.style.color="#5d5d5d";jscolor.picker.btnOk.className="DEXT_fiVe_EdiTor_font";jscolor.picker.btnOk.style.fontSize="13px";jscolor.picker.btnCancle.setAttribute("type","button");
jscolor.picker.btnCancle.setAttribute("id","cp_btn_cancle");jscolor.picker.btnCancle.setAttribute("value",parent.DEXTTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.close);if(a=0==parent.DEXTTOP.DEXT5.UserAgent.os.name.toLowerCase().indexOf("mac")&&"safari"==parent.DEXTTOP.DEXT5.UserAgent.browser.name.toLowerCase())jscolor.picker.btnOk.style.height="24px";parent.DEXTTOP.DEXT5.browser.mobile||a?(jscolor.picker.btnCancle.style.width="40px",a&&(jscolor.picker.btnCancle.style.height="24px")):jscolor.picker.btnCancle.style.width=
parent.DEXTTOP.DEXT5.browser.ie?"54px":"51px";jscolor.picker.btnCancle.style.color="#5d5d5d";jscolor.picker.btnCancle.className="DEXT_fiVe_EdiTor_font";jscolor.picker.btnCancle.style.fontSize="13px";jscolor.picker.boxC.appendChild(jscolor.picker.lbColor2);jscolor.picker.boxC.appendChild(jscolor.picker.boxHEX);jscolor.picker.bottom.appendChild(jscolor.picker.boxC);jscolor.picker.select.onchange=function(){"hex"==jscolor.picker.select.value?(jscolor.picker.lbColor.value="",jscolor.picker.lbColor2.style.backgroundColor=
"#ffffff",jscolor.picker.boxC.removeChild(jscolor.picker.boxRGB),jscolor.picker.boxHEX.style.display="inline-block",jscolor.picker.boxC.appendChild(jscolor.picker.boxHEX),jscolor.picker.lbColor.focus()):"rgb"==jscolor.picker.select.value&&(jscolor.picker.lbColorR.value="",jscolor.picker.lbColorG.value="",jscolor.picker.lbColorB.value="",jscolor.picker.lbColor2.style.backgroundColor="#ffffff",jscolor.picker.boxC.removeChild(jscolor.picker.boxHEX),jscolor.picker.boxRGB.style.display="inline-block",
jscolor.picker.boxC.appendChild(jscolor.picker.boxRGB),jscolor.picker.lbColorR.focus())};jscolor.picker.inbottom.appendChild(jscolor.picker.select);jscolor.picker.inbottom.appendChild(jscolor.picker.btnOk);jscolor.picker.inbottom.appendChild(jscolor.picker.btnCancle);jscolor.picker.bottom.appendChild(jscolor.picker.inbottom);jscolor.picker.boxB.appendChild(jscolor.picker.bottom);jscolor.picker.boxB.setAttribute("id","color_picker")}var c=jscolor.picker;c.box.onmouseup=c.box.onmousedown=function(){v=
!0};c.box.onmousemove=function(c){if(p||q)p&&A(c),q&&B(c),document.selection?document.selection.empty():window.getSelection&&window.getSelection().removeAllRanges(),w()};"ontouchstart"in window&&c.box.addEventListener("touchmove",function(c){var b={offsetX:c.touches[0].pageX-r.X,offsetY:c.touches[0].pageY-r.Y};if(p||q)p&&A(b),q&&B(b),w();c.stopPropagation();c.preventDefault()},!1);c.padM.onmouseup=c.padM.onmouseout=function(){p&&(p=!1,jscolor.fireEvent(m,"change"))};c.padM.onmousedown=function(c){switch(t){case 0:0===
e.hsv[2]&&e.fromHSV(null,null,1);break;case 1:0===e.hsv[1]&&e.fromHSV(null,1,null)}q=!1;p=!0;A(c);w()};"ontouchstart"in window&&c.padM.addEventListener("touchstart",function(c){r={X:c.target.offsetParent.offsetLeft,Y:c.target.offsetParent.offsetTop};this.onmousedown({offsetX:c.touches[0].pageX-r.X,offsetY:c.touches[0].pageY-r.Y})});c.sldM.onmouseup=c.sldM.onmouseout=function(){q&&(q=!1,jscolor.fireEvent(m,"change"))};c.sldM.onmousedown=function(c){p=!1;q=!0;B(c);w()};"ontouchstart"in window&&c.sldM.addEventListener("touchstart",
function(c){r={X:c.target.offsetParent.offsetLeft,Y:c.target.offsetParent.offsetTop};this.onmousedown({offsetX:c.touches[0].pageX-r.X,offsetY:c.touches[0].pageY-r.Y})});a=H(e);c.box.style.width=a[0]+"px";c.box.style.height=a[1]+"px";c.boxB.style.position="absolute";c.boxB.style.clear="both";c.boxB.style.left=b-6+"px";c.boxB.style.top=d+2+"px";c.boxB.style.zIndex=e.pickerZIndex;c.boxB.style.border=e.pickerBorder+"px solid";c.boxB.style.borderColor=e.pickerBorderColor;c.boxB.style.background=e.pickerFaceColor;
c.pad.style.width=jscolor.images.pad[0]+"px";c.pad.style.height=jscolor.images.pad[1]+"px";c.padB.style.position="absolute";c.padB.style.left=e.pickerFace+"px";c.padB.style.top=e.pickerFace+"px";c.padB.style.border=e.pickerInset+"px solid";c.padB.style.borderColor=e.pickerInsetColor;c.padM.style.position="absolute";c.padM.style.left="0";c.padM.style.top="0";c.padM.style.width=e.pickerFace+2*e.pickerInset+jscolor.images.pad[0]+"px";c.padM.style.height=c.box.style.height;c.padM.style.cursor="crosshair";
c.sld.style.overflow="hidden";c.sld.style.width=jscolor.images.sld[0]+"px";c.sld.style.height=jscolor.images.sld[1]+"px";c.sldB.style.display=e.slider?"block":"none";c.sldB.style.position="absolute";c.sldB.style.right=e.pickerFace+"px";c.sldB.style.top=e.pickerFace+"px";c.sldB.style.border=e.pickerInset+"px solid";c.sldB.style.borderColor=e.pickerInsetColor;c.sldM.style.display=e.slider?"block":"none";c.sldM.style.position="absolute";c.sldM.style.right="3px";c.sldM.style.top="0";c.sldM.style.width=
jscolor.images.sld[0]+jscolor.images.arrow[0]+2*e.pickerInset+"px";c.sldM.style.height=c.box.style.height;try{c.sldM.style.cursor="pointer"}catch(g){c.sldM.style.cursor="hand"}a=function(b){b=b?b:window.event;if(13==b.keyCode)return k(),!1;b.shiftKey&&9==b.keyCode&&setTimeout(function(){c.btnCancle.focus()},0)};c.lbColor.onkeydown=a;c.lbColorR.onkeydown=a;c.btn.style.display=e.pickerClosable?"block":"none";c.btn.style.position="absolute";c.btn.style.left=e.pickerFace+"px";c.btn.style.bottom=e.pickerFace+
"px";c.btn.style.padding="0 15px";c.btn.style.height="18px";c.btn.style.border=e.pickerInset+"px solid";(function(){var b=e.pickerInsetColor.split(/\s+/);c.btn.style.borderColor=2>b.length?b[0]:b[1]+" "+b[0]+" "+b[0]+" "+b[1]})();c.btn.style.color=e.pickerButtonColor;c.btn.style.font="12px sans-serif";c.btn.style.textAlign="center";try{c.btn.style.cursor="pointer"}catch(h){c.btn.style.cursor="hand"}c.btn.onmousedown=function(){e.hidePicker()};c.btnS.style.lineHeight=c.btn.style.height;var k=function(){var b=
"",a=c.select.value;if("hex"==a){if(b=c.lbColor.value,null!=b.match(/[^a-f\d]/gi)){alert(parent.DEXTTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg);setTimeout(function(){c.lbColor.focus()},0);return}}else{var d=c.lbColorR.value,e=c.lbColorG.value,b=c.lbColorB.value;if(0>=d.length||null!=d.match(/[^0-9\d]/gi)){alert(parent.DEXTTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg);setTimeout(function(){c.lbColorR.focus()},0);return}if(0>=e.length||null!=e.match(/[^0-9\d]/gi)){alert(parent.DEXTTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg);
setTimeout(function(){c.lbColorG.focus()},0);return}if(0>=b.length||null!=b.match(/[^0-9\d]/gi)){alert(parent.DEXTTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg);setTimeout(function(){c.lbColorB.focus()},0);return}d=parseInt(d,10).toString(16);1==d.length&&(d="0"+d);e=parseInt(e,10).toString(16);1==e.length&&(e="0"+e);b=parseInt(b,10).toString(16);1==b.length&&(b="0"+b);b=d+e+b}b=b.replace("#","");d=b.match(/[a-f\d]/gi);if(0>=b.length||null==d)alert(parent.DEXTTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg),
"hex"==a?setTimeout(function(){c.lbColor.focus()},0):setTimeout(function(){c.lbColorR.focus()},0);else if(3==d.length&&(b=d[0]+d[0]+d[1]+d[1]+d[2]+d[2]),3!=d.length&&6!=d.length)alert(parent.DEXTTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg),"hex"==a?setTimeout(function(){c.lbColor.focus()},0):setTimeout(function(){c.lbColorR.focus()},0);else if(-1==b.indexOf("#")&&(b="#"+b),7!=b.length)alert(parent.DEXTTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg),"hex"==a?setTimeout(function(){c.lbColor.focus()},
0):setTimeout(function(){c.lbColorR.focus()},0);else{"#000000"==b&&(b="black");b=b.toLowerCase();parent.DEXTTOP.DEXT5.browser.LocalStorageSupported&&(a=parent.DEXTTOP.DEXTWIN.localStorage.getItem(parent.DEXTTOP.G_CURREDITOR.recentlyColorName),null!=a?(a=a.split(","),-1!=a.indexOf(b)&&a.splice(a.indexOf(b),1),a.unshift(b),9<a.length&&(a.reverse(),a.shift(),a.reverse()),parent.DEXTTOP.DEXTWIN.localStorage.setItem(parent.DEXTTOP.G_CURREDITOR.recentlyColorName,a)):parent.DEXTTOP.DEXTWIN.localStorage.setItem(parent.DEXTTOP.G_CURREDITOR.recentlyColorName,
b));void 0!==jscolor.styleColor||""!==jscolor.styleColor?jscolor.clickedElem.style[jscolor.styleColor]=b:(a=iframeDoc.createElement("input"),a.type="hidden",a.value=b,a.id="hidden_color",iframeDoc.body.appendChild(a));if(void 0!==jscolor.actionType||""!==jscolor.actionType)"font_color"==jscolor.actionType||"detail_font_color"==jscolor.actionType?parent.command_fontColor(parent.DEXTTOP.G_CURREDITOR.ID,parent.document.getElementById("dext5_design_"+parent.DEXTTOP.G_CURREDITOR.ID),b):"font_bg_color"==
jscolor.actionType||"detail_font_bg_color"==jscolor.actionType?parent.command_fontBgColor(parent.DEXTTOP.G_CURREDITOR.ID,parent.document.getElementById("dext5_design_"+parent.DEXTTOP.G_CURREDITOR.ID),b):"doc_bg_color"==jscolor.actionType?parent.command_docBGColor(parent.DEXTTOP.G_CURREDITOR.ID,parent.document.getElementById("dext5_design_"+parent.DEXTTOP.G_CURREDITOR.ID),b):"cell_bg_color"==jscolor.actionType||"detail_cell_bg_color"==jscolor.actionType?parent.command_cellBGColor(parent.DEXTTOP.G_CURREDITOR.ID,
parent.document.getElementById("dext5_design_"+parent.DEXTTOP.G_CURREDITOR.ID),b):"line_color"==jscolor.actionType&&jscolor.excuteFn&&jscolor.excuteFn();jscolor.clickedElem=null;jscolor.styleColor="";jscolor.actionType="";jscolor.excuteFn=null;parent.document.body.removeChild(parent.document.getElementById("dext_color_back"));parent.document.body.removeChild(parent.document.getElementById("popupCover"))}};c.btnOk.style.margin="0 2px 0 4px";c.btnOk.onkeydown=function(b){b=b?b:window.event;if(13==b.keyCode)return k(),
!1};c.btnOk.onmousedown=k;c.lbColor2.style.margin="0 2px 0 0";c.bottom.style.margin="0 0 3px 6px";var n=function(){jscolor.clickedElem=null;jscolor.styleColor="";jscolor.actionType="";jscolor.excuteFn=null;document.getElementById("color_picker").style.display="none";parent.document.getElementById("popupCover").style.height="200px"};c.btnCancle.onkeydown=function(b){b=b?b:window.event;13==b.keyCode?n():0==b.shiftKey&&9==b.keyCode&&("hex"==c.select.value?setTimeout(function(){c.lbColor.focus()},0):
"rgb"==c.select.value&&setTimeout(function(){c.lbColorR.focus()},0))};c.btnCancle.onmousedown=n;switch(t){case 0:var u="hs2.png";break;case 1:u="hv.png"}c.padM.style.backgroundImage="url('"+jscolor.getDir()+"cross.gif')";c.padM.style.backgroundRepeat="no-repeat";c.pad.style.backgroundImage="url('"+jscolor.getDir()+u+"')";c.pad.style.backgroundRepeat="no-repeat";c.pad.style.backgroundPosition="0 0";I();J();jscolor.picker.owner=e;document.getElementsByTagName("body")[0].appendChild(c.boxB);"hex"==jscolor.picker.select.value?
jscolor.picker.lbColor.focus():jscolor.picker.lbColorR.focus()}function H(b){return[2*b.pickerInset+2*b.pickerFace+jscolor.images.pad[0]+(b.slider?2*b.pickerInset+2*jscolor.images.arrow[0]+jscolor.images.sld[0]:0),b.pickerClosable?4*b.pickerInset+3*b.pickerFace+jscolor.images.pad[1]+b.pickerButtonHeight:2*b.pickerInset+2*b.pickerFace+jscolor.images.pad[1]]}function I(){switch(t){case 0:var b=1;break;case 1:b=2}var a=Math.round(e.hsv[0]/6*(jscolor.images.pad[0]-1)),b=Math.round((1-e.hsv[b])*(jscolor.images.pad[1]-
1));jscolor.picker.padM.style.backgroundPosition=e.pickerFace+e.pickerInset+a-Math.floor(jscolor.images.cross[0]/2)+"px "+(e.pickerFace+e.pickerInset+b-Math.floor(jscolor.images.cross[1]/2))+"px";a=jscolor.picker.sld.childNodes;switch(t){case 0:for(var d=z(e.hsv[0],e.hsv[1],1),b=0;b<a.length;b+=1)a[b].style.backgroundColor="rgb("+d[0]*(1-b/a.length)*100+"%,"+d[1]*(1-b/a.length)*100+"%,"+d[2]*(1-b/a.length)*100+"%)";break;case 1:var f,l=[e.hsv[2],0,0],b=Math.floor(e.hsv[0]),c=b%2?e.hsv[0]-b:1-(e.hsv[0]-
b);switch(b){case 6:case 0:d=[0,1,2];break;case 1:d=[1,0,2];break;case 2:d=[2,0,1];break;case 3:d=[2,1,0];break;case 4:d=[1,2,0];break;case 5:d=[0,2,1]}for(b=0;b<a.length;b+=1)f=1-1/(a.length-1)*b,l[1]=l[0]*(1-f*c),l[2]=l[0]*(1-f),a[b].style.backgroundColor="rgb("+100*l[d[0]]+"%,"+100*l[d[1]]+"%,"+100*l[d[2]]+"%)"}}function J(){switch(t){case 0:var b=2;break;case 1:b=1}b=Math.round((1-e.hsv[b])*(jscolor.images.sld[1]-1));jscolor.picker.sldM.style.backgroundPosition="0 "+(e.pickerFace+e.pickerInset+
b-Math.floor(jscolor.images.arrow[1]/2))+"px"}function y(){return jscolor.picker&&jscolor.picker.owner===e}function L(){m!==d&&e.importColor()}function A(b){var a=jscolor.getRelMousePos(b);b=a.x-e.pickerFace-e.pickerInset;a=a.y-e.pickerFace-e.pickerInset;switch(t){case 0:e.fromHSV(6/(jscolor.images.pad[0]-1)*b,1-a/(jscolor.images.pad[1]-1),null,C);break;case 1:e.fromHSV(6/(jscolor.images.pad[0]-1)*b,null,1-a/(jscolor.images.pad[1]-1),C)}}function B(b){b=jscolor.getRelMousePos(b).y-e.pickerFace-e.pickerInset;
switch(t){case 0:e.fromHSV(null,null,1-b/(jscolor.images.sld[1]-1),D);break;case 1:e.fromHSV(null,1-b/(jscolor.images.sld[1]-1),null,D)}}function w(){e.onImmediateChange&&("string"===typeof e.onImmediateChange?new Function(e.onImmediateChange):e.onImmediateChange).call(e)}jscolor.clickedElem=a;jscolor.styleColor=n;jscolor.actionType=x;jscolor.excuteFn=G;this.slider=this.caps=this.hash=this.adjust=this.required=!0;this.styleElement=this.valueElement=d;this.onImmediateChange=null;this.hsv=[0,0,1];this.rgb=
[1,1,1];this.minH=0;this.maxH=6;this.minS=0;this.maxS=1;this.minV=0;this.maxV=1;this.pickerOnfocus=!1;this.pickerMode="HSV";this.pickerPosition="bottom";this.pickerSmartPosition=!1;this.pickerButtonHeight=0;this.pickerClosable=!1;this.pickerCloseText="Close";this.pickerButtonColor="ButtonText";this.pickerFace=6;this.pickerFaceColor="ThreeDFace";this.pickerBorder=1;this.pickerBorderColor="ThreeDHighlight ThreeDShadow ThreeDShadow ThreeDHighlight";this.pickerInset=1;this.pickerInsetColor="ThreeDShadow ThreeDShadow ThreeDShadow ThreeDShadow";
this.pickerZIndex=15E3;for(var E in f)f.hasOwnProperty(E)&&(this[E]=f[E]);this.hidePicker=function(){y()&&(delete jscolor.picker.owner,document.getElementsByTagName("body")[0].removeChild(jscolor.picker.boxB))};this.showPicker=function(){if(!y()){var b=jscolor.getElementPos(d),a=jscolor.getElementSize(d),e=jscolor.getViewPos(),f=jscolor.getViewSize(),l=H(this),c,g,h;switch(this.pickerPosition.toLowerCase()){case "left":c=1;g=0;h=-1;break;case "right":c=1;g=0;h=1;break;case "top":c=0;g=1;h=-1;break;
default:c=0,h=g=1}var k=(a[g]+l[g])/2,b=this.pickerSmartPosition?[-e[c]+b[c]+l[c]>f[c]?-e[c]+b[c]+a[c]/2>f[c]/2&&0<=b[c]+a[c]-l[c]?b[c]+a[c]-l[c]:b[c]:b[c],-e[g]+b[g]+a[g]+l[g]-k+k*h>f[g]?-e[g]+b[g]+a[g]/2>f[g]/2&&0<=b[g]+a[g]-k-k*h?b[g]+a[g]-k-k*h:b[g]+a[g]-k+k*h:0<=b[g]+a[g]-k+k*h?b[g]+a[g]-k+k*h:b[g]+a[g]-k-k*h]:[b[c],b[g]+a[g]-k+k*h];K(b[c],b[g])}};this.importColor=function(){m?this.adjust?!this.required&&/^\s*$/.test(m.value)?(m.value="",h.style.backgroundImage=h.jscStyle.backgroundImage,h.style.backgroundColor=
h.jscStyle.backgroundColor,h.style.color=h.jscStyle.color,this.exportColor(u|F)):this.fromString(m.value):this.fromString(m.value,u)||(h.style.backgroundImage=h.jscStyle.backgroundImage,h.style.backgroundColor=h.jscStyle.backgroundColor,h.style.color=h.jscStyle.color,this.exportColor(u|F)):this.exportColor()};this.exportColor=function(b){if(!(b&u)&&m){var a=this.toString(),d=a;this.caps&&(a=a.toUpperCase());null!=jscolor.picker.lbColor&&(jscolor.picker.lbColor.value=a);if(null!=jscolor.picker.lbColorB){a=
d.match(/[a-f\d]/gi);3==a.length&&(d=a[0]+a[0]+a[1]+a[1]+a[2]+a[2]);var a=d.match(/[a-f\d]{2}/gi),d=parseInt(a[0],16),e=parseInt(a[1],16),a=parseInt(a[2],16);jscolor.picker.lbColorR.value=d;jscolor.picker.lbColorG.value=e;jscolor.picker.lbColorB.value=a}}b&F||!h||null==jscolor.picker.lbColor2||(jscolor.picker.lbColor2.style.backgroundColor="#"+this.toString());b&D||!y()||I();b&C||!y()||J()};this.fromHSV=function(b,a,d,e){null!==b&&(b=Math.max(0,this.minH,Math.min(6,this.maxH,b)));null!==a&&(a=Math.max(0,
this.minS,Math.min(1,this.maxS,a)));null!==d&&(d=Math.max(0,this.minV,Math.min(1,this.maxV,d)));this.rgb=z(null===b?this.hsv[0]:this.hsv[0]=b,null===a?this.hsv[1]:this.hsv[1]=a,null===d?this.hsv[2]:this.hsv[2]=d);this.exportColor(e)};this.fromRGB=function(b,a,d,e){null!==b&&(b=Math.max(0,Math.min(1,b)));null!==a&&(a=Math.max(0,Math.min(1,a)));null!==d&&(d=Math.max(0,Math.min(1,d)));b=null===b?this.rgb[0]:b;a=null===a?this.rgb[1]:a;var f=null===d?this.rgb[2]:d,c=Math.min(Math.min(b,a),f);d=Math.max(Math.max(b,
a),f);var g=d-c;0===g?b=[null,0,d]:(b=b===c?3+(f-a)/g:a===c?5+(b-f)/g:1+(a-b)/g,b=[6===b?0:b,g/d,d]);null!==b[0]&&(this.hsv[0]=Math.max(0,this.minH,Math.min(6,this.maxH,b[0])));0!==b[2]&&(this.hsv[1]=null===b[1]?null:Math.max(0,this.minS,Math.min(1,this.maxS,b[1])));this.hsv[2]=null===b[2]?null:Math.max(0,this.minV,Math.min(1,this.maxV,b[2]));b=z(this.hsv[0],this.hsv[1],this.hsv[2]);this.rgb[0]=b[0];this.rgb[1]=b[1];this.rgb[2]=b[2];this.exportColor(e)};this.fromString=function(a,d){var e="More".match(/^\W*([0-9A-F]{3}([0-9A-F]{3})?)\W*$/i);
return e?(6===e[1].length?this.fromRGB(parseInt(e[1].substr(0,2),16)/255,parseInt(e[1].substr(2,2),16)/255,parseInt(e[1].substr(4,2),16)/255,d):this.fromRGB(parseInt(e[1].charAt(0)+e[1].charAt(0),16)/255,parseInt(e[1].charAt(1)+e[1].charAt(1),16)/255,parseInt(e[1].charAt(2)+e[1].charAt(2),16)/255,d),!0):!1};this.toString=function(){return(256|Math.round(255*this.rgb[0])).toString(16).substr(1)+(256|Math.round(255*this.rgb[1])).toString(16).substr(1)+(256|Math.round(255*this.rgb[2])).toString(16).substr(1)};
var e=this,t="hvs"===this.pickerMode.toLowerCase()?1:0,v=!1,m=jscolor.fetchElement(this.valueElement),h=jscolor.fetchElement(this.styleElement),p=!1,q=!1,r={},u=1,F=2,D=4,C=8;jscolor.addEvent(d,"click",function(){e.showPicker()});jscolor.addEvent(d,"blur",function(){v?v=!1:window.setTimeout(function(){v||(m===d&&e.importColor(),e.pickerOnfocus&&e.hidePicker());v=!1},0)});m&&(f=function(){e.fromString(m.value,u);w()},jscolor.addEvent(m,"keyup",f),jscolor.addEvent(m,"input",f),jscolor.addEvent(m,"blur",
L),m.setAttribute("autocomplete","off"));h&&(h.jscStyle={backgroundImage:h.style.backgroundImage,backgroundColor:h.style.backgroundColor,color:h.style.color});switch(t){case 0:jscolor.requireImage("hs2.png");break;case 1:jscolor.requireImage("hv.png")}jscolor.requireImage("cross.gif");jscolor.requireImage("arrow.gif");this.importColor()}};parent.DEXTTOP.DEXT5.util.addEvent(document,"contextmenu",function(d){parent.DEXTTOP.DEXT5.util.cancelEvent(d)});jscolor.install();
